package DartModel.DART_UI_module.v1_1_1.src;

/*********************************/
/*                               */
/*   Importing all Nsl classes   */
/*                               */
/*********************************/

import nslj.src.system.*;
import nslj.src.cmd.*;
import nslj.src.lang.*;
import nslj.src.math.*;
import nslj.src.display.*;
import nslj.src.display.j3d.*;

/*********************************/

public class DART_UI_module extends NslJavaModule{

//NSL Version: 3_0_n
//Sif Version: 9
//libNickName: DartModel
//moduleName:  DART_UI_module
//versionName: 1_1_1
//floatSubModules: true


//variables 
public  NslDinDouble0 throw_in; // Throw direction
public  NslDinDouble0 p_in; // Prism angle [0:30]
public  NslDinDouble0 s_in; // Strategy: [0:1] over/under
private  NslDouble1 throw_dart; // graph parameter

//methods 
public void initModule()
{
	nslAddUserCanvas("dartFrame", "dartCanvas", throw_dart,0,1,"DartModel/NslDartGraphCanvas/v1_1_1/src","DartGraph");
	initTrainEpoch();
	throw_dart.set(  -1);
}

public void initTrainEpoch() 
{
	nslRemoveFromLocalProtocols("manual");
	nslRemoveFromLocalProtocols("basic");
	nslRemoveFromLocalProtocols("transfer");
	nslRemoveFromLocalProtocols("calibration");
}  

public void initRunEpoch() 
{
	nslAddProtocolRecursiveUp("basic");
	nslAddProtocolRecursiveUp("transfer");
	nslAddProtocolRecursiveUp("calibration");     
}

//public void initRun() 
//{
//	throw_dart = -1;
//}
   
public void endRun()
{
	throw_dart.set(0,   system.getFinishedEpochs());
	throw_dart.set(1,   throw_in);
	throw_dart.set(2,   p_in);
	throw_dart.set(3,   s_in);
}
public void makeConn(){
}

	/******************************************************/
	/*                                                    */
	/* Generated by nslc.src.NslCompiler. Do not edit these lines! */
	/*                                                    */
	/******************************************************/

	/* Constructor and related methods */
	/* makeinst() declared variables */

	/* Formal parameters */

	/* Temporary variables */

	/* GENERIC CONSTRUCTOR: */
	public DART_UI_module(String nslName, NslModule nslParent)
{
		super(nslName, nslParent);
		initSys();
		makeInstDART_UI_module(nslName, nslParent);
	}

	public void makeInstDART_UI_module(String nslName, NslModule nslParent)
{ 
		Object[] nslArgs=new Object[]{};
		callFromConstructorTop(nslArgs);
		throw_in = new NslDinDouble0("throw_in", this);
		p_in = new NslDinDouble0("p_in", this);
		s_in = new NslDinDouble0("s_in", this);
		throw_dart = new NslDouble1("throw_dart", this, 4);
		callFromConstructorBottom();
	}

	/******************************************************/
	/*                                                    */
	/* End of automatic declaration statements.           */
	/*                                                    */
	/******************************************************/


}//end DART_UI_module

