package BackPropModel.TrainManager.v1_1_1.src;

/*********************************/
/*                               */
/*   Importing all Nsl classes   */
/*                               */
/*********************************/

import nslj.src.system.*;
import nslj.src.cmd.*;
import nslj.src.lang.*;
import nslj.src.math.*;
import nslj.src.display.*;
import nslj.src.display.j3d.*;

/*********************************/

public class TrainManager extends NslJavaModule{

//NSL Version: 3_0_n
//Sif Version: 9
//libNickName: BackPropModel
//moduleName:  TrainManager
//versionName: 1_1_1
//floatSubModules: true


//variables 
public  NslDoutFloat1 dInput; // 
public  NslDoutFloat1 dOutput; // 
private  NslFloat2 pInput; // 
private  NslFloat2 pOutput; // 
private int counter=0; // 

//methods 
public void initModule()
{
	pInput.nslSetAccess('W');
	pOutput.nslSetAccess('W');
	nslAddAreaCanvas("backPropOut", "input", dInput, 0.0, 1.0);
	nslAddAreaCanvas("backPropOut", "desired", dOutput, 0.0, 1.0);
}

public void simTrain() 
{
	counter++;
	int pat = counter%nPats;
	dInput.set(  __tempTrainManager0.setReference(pInput.get(pat)));
	dOutput.set(  __tempTrainManager1.setReference(pOutput.get(pat)));
}
public void makeConn(){
}

	/******************************************************/
	/*                                                    */
	/* Generated by nslc.src.NslCompiler. Do not edit these lines! */
	/*                                                    */
	/******************************************************/

	/* Constructor and related methods */
	/* makeinst() declared variables */

	/* Formal parameters */
	int nPats;
	int inSize;
	int outSize;

	/* Temporary variables */
		NslFloat1 __tempTrainManager0 = new NslFloat1(1);
		NslFloat1 __tempTrainManager1 = new NslFloat1(1);

	/* GENERIC CONSTRUCTOR: */
	public TrainManager(String nslName, NslModule nslParent, int nPats, int inSize, int outSize)
{
		super(nslName, nslParent);
		this.nPats=nPats;
		this.inSize=inSize;
		this.outSize=outSize;
		initSys();
		makeInstTrainManager(nslName, nslParent, nPats, inSize, outSize);
	}

	public void makeInstTrainManager(String nslName, NslModule nslParent, int nPats, int inSize, int outSize)
{ 
		Object[] nslArgs=new Object[]{nPats, inSize, outSize};
		callFromConstructorTop(nslArgs);
		dInput = new NslDoutFloat1("dInput", this, inSize);
		dOutput = new NslDoutFloat1("dOutput", this, outSize);
		pInput = new NslFloat2("pInput", this, nPats, inSize);
		pOutput = new NslFloat2("pOutput", this, nPats, outSize);
		callFromConstructorBottom();
	}

	/******************************************************/
	/*                                                    */
	/* End of automatic declaration statements.           */
	/*                                                    */
	/******************************************************/


}//end TrainManager

