package DomineyModel.TNChange.v1_1_1.src;

/*********************************/
/*                               */
/*   Importing all Nsl classes   */
/*                               */
/*********************************/

import nslj.src.system.*;
import nslj.src.cmd.*;
import nslj.src.lang.*;
import nslj.src.math.*;
import nslj.src.display.*;
import nslj.src.display.j3d.*;

/*********************************/

public class TNChange extends NslModule{

//NSL Version: 3_0_n
//Sif Version: 9
//libNickName: DomineyModel
//moduleName:  TNChange
//versionName: 1_1_1
//floatSubModules: true


//variables 
public  NslDinFloat0 fefgate; // 
public  NslDinFloat0 ebn; // 
public  NslDinFloat0 opposite_ebn; // 
public  NslDinFloat0 tnDelta; // 
public  NslDoutFloat0 tn; // 
public  NslDoutFloat0 tnChange; // 
private NslFloat0 tn_k1; // 
private NslFloat0 tnDelay1_tm; // 
private NslFloat0 tnDelay1; // 

//methods 
public void initRun() 
{
	if (system.debug>=13) 
	{
		system.nslPrintln("debug:TNChange:initRun");
	}
	tn.set(0);
	tnChange.set(0);
	tnDelay1.set(154); // use to be TNDELAY
	tn.set(154);
	tnChange.set(0);

	tn_k1.set(.01527778);
	tnDelay1_tm.set(.006);
}

public void simRun() 
{
	tnDelay1.set(system.nsldiff.eval(tnDelay1,tnDelay1_tm, __tempTNChange1.setReference(__tempTNChange0.setReference(-tnDelay1.get()).get()+tn.get()) ));
	//On each timestep,the tonic component uppdated by 2.75*(change in Theta).
	// Change in Theta is angular velocity * time =
	//			   opposite_ebn*(1/R)  * (simuation time step)
	tn.set(  __tempTNChange7.setReference(__tempTNChange6.setReference(__tempTNChange5.setReference(tn.get()+__tempTNChange2.setReference(tn_k1.get()*ebn.get()).get()).get()-__tempTNChange3.setReference(tn_k1.get()*opposite_ebn.get()).get()).get()-__tempTNChange4.setReference(fefgate.get()*tnDelta.get()).get()));
	tnChange.set(  __tempTNChange8.setReference(tn.get()-tnDelay1.get()) );

	if (system.debug>=13) 
	{
		system.nslPrintln("TNChange:tn: "+tn.toString());
		system.nslPrintln("TNChange:tnChange: "+tnChange.toString());
	}
}
public void makeConn(){
}

	/******************************************************/
	/*                                                    */
	/* Generated by nslc.src.NslCompiler. Do not edit these lines! */
	/*                                                    */
	/******************************************************/

	/* Constructor and related methods */
	/* makeinst() declared variables */

	/* Formal parameters */

	/* Temporary variables */
		NslFloat0 __tempTNChange0 = new NslFloat0();
		NslFloat0 __tempTNChange1 = new NslFloat0();
		NslFloat0 __tempTNChange2 = new NslFloat0();
		NslFloat0 __tempTNChange3 = new NslFloat0();
		NslFloat0 __tempTNChange4 = new NslFloat0();
		NslFloat0 __tempTNChange5 = new NslFloat0();
		NslFloat0 __tempTNChange6 = new NslFloat0();
		NslFloat0 __tempTNChange7 = new NslFloat0();
		NslFloat0 __tempTNChange8 = new NslFloat0();

	/* GENERIC CONSTRUCTOR: */
	public TNChange(String nslName, NslModule nslParent)
{
		super(nslName, nslParent);
		initSys();
		makeInstTNChange(nslName, nslParent);
	}

	public void makeInstTNChange(String nslName, NslModule nslParent)
{ 
		Object[] nslArgs=new Object[]{};
		callFromConstructorTop(nslArgs);
		fefgate = new NslDinFloat0("fefgate", this);
		ebn = new NslDinFloat0("ebn", this);
		opposite_ebn = new NslDinFloat0("opposite_ebn", this);
		tnDelta = new NslDinFloat0("tnDelta", this);
		tn = new NslDoutFloat0("tn", this);
		tnChange = new NslDoutFloat0("tnChange", this);
		tn_k1 = new NslFloat0("tn_k1", this);
		tnDelay1_tm = new NslFloat0("tnDelay1_tm", this);
		tnDelay1 = new NslFloat0("tnDelay1", this);
		callFromConstructorBottom();
	}

	/******************************************************/
	/*                                                    */
	/* End of automatic declaration statements.           */
	/*                                                    */
	/******************************************************/


}//end TNChange

