package DomineyModel.MN.v1_1_1.src;

/*********************************/
/*                               */
/*   Importing all Nsl classes   */
/*                               */
/*********************************/

import nslj.src.system.*;
import nslj.src.cmd.*;
import nslj.src.lang.*;
import nslj.src.math.*;
import nslj.src.display.*;
import nslj.src.display.j3d.*;

/*********************************/

public class MN extends NslModule{

//NSL Version: 3_0_n
//Sif Version: 9
//libNickName: DomineyModel
//moduleName:  MN
//versionName: 1_1_1
//floatSubModules: true


//variables 
public  NslDinFloat0 ebn; // 
public  NslDinFloat0 tn; // 
public  NslDoutFloat0 mn; // 

//methods 
public void initRun() 
{
	mn.set(0);
}

public void simRun() 
{
	mn.set(  __tempMN0.setReference(ebn.get()+tn.get()) );

	if (system.debug>=11) 
	{
		system.nslPrintln("MN:simRun:mn"+mn.toString());
	}
}
public void makeConn(){
}

	/******************************************************/
	/*                                                    */
	/* Generated by nslc.src.NslCompiler. Do not edit these lines! */
	/*                                                    */
	/******************************************************/

	/* Constructor and related methods */
	/* makeinst() declared variables */

	/* Formal parameters */

	/* Temporary variables */
		NslFloat0 __tempMN0 = new NslFloat0();

	/* GENERIC CONSTRUCTOR: */
	public MN(String nslName, NslModule nslParent)
{
		super(nslName, nslParent);
		initSys();
		makeInstMN(nslName, nslParent);
	}

	public void makeInstMN(String nslName, NslModule nslParent)
{ 
		Object[] nslArgs=new Object[]{};
		callFromConstructorTop(nslArgs);
		ebn = new NslDinFloat0("ebn", this);
		tn = new NslDinFloat0("tn", this);
		mn = new NslDoutFloat0("mn", this);
		callFromConstructorBottom();
	}

	/******************************************************/
	/*                                                    */
	/* End of automatic declaration statements.           */
	/*                                                    */
	/******************************************************/


}//end MN

