package DomineyModel.STM.v1_1_1.src;

/*********************************/
/*                               */
/*   Importing all Nsl classes   */
/*                               */
/*********************************/

import nslj.src.system.*;
import nslj.src.cmd.*;
import nslj.src.lang.*;
import nslj.src.math.*;
import nslj.src.display.*;
import nslj.src.display.j3d.*;

/*********************************/

public class STM extends NslModule{

//NSL Version: 3_0_n
//Sif Version: 9
//libNickName: DomineyModel
//moduleName:  STM
//versionName: 1_1_1
//floatSubModules: true


//variables 
public  NslDoutFloat2 stm; // 
public  NslDoutFloat2 weights; // 
private NslFloat0 stm_k1; // 
private  NslFloat1 weighttopo; // 
private  NslFloat1 stmtopo; // 

//methods 
public void initRun() 
{
	stm_k1.set(0.32);
	weighttopo.set(0);
	stmtopo.set(0);
	weights.set(0);
	stm.set(0);

 	if ((direction==1)||(direction==3))
	{
		weighttopo.set(0,   5.7);
		weighttopo.set(1,   4.275);
		weighttopo.set(2,   2.85);
		weighttopo.set(3,   1.425);
		stmtopo.set(0, __tempSTM1.setReference(stm_k1.get()*__tempSTM0.setReference(weighttopo.get(0)).get()));
		stmtopo.set(1, __tempSTM3.setReference(stm_k1.get()*__tempSTM2.setReference(weighttopo.get(1)).get()));
		stmtopo.set(2, __tempSTM5.setReference(stm_k1.get()*__tempSTM4.setReference(weighttopo.get(2)).get()));
		stmtopo.set(3, __tempSTM7.setReference(stm_k1.get()*__tempSTM6.setReference(weighttopo.get(3)).get()));
	}
	if ((direction==2)||(direction==4))
	{
		weighttopo.set(5,   1.425);
		weighttopo.set(6,   2.85);
		weighttopo.set(7,   4.275);
		weighttopo.set(8,   5.7);
		stmtopo.set(5, __tempSTM9.setReference(stm_k1.get()*__tempSTM8.setReference(weighttopo.get(5)).get()));
		stmtopo.set(6, __tempSTM11.setReference(stm_k1.get()*__tempSTM10.setReference(weighttopo.get(6)).get()));
		stmtopo.set(7, __tempSTM13.setReference(stm_k1.get()*__tempSTM12.setReference(weighttopo.get(7)).get()));
		stmtopo.set(8, __tempSTM15.setReference(stm_k1.get()*__tempSTM14.setReference(weighttopo.get(8)).get()));
	}
	if ((direction==1)||(direction==2))
	{
		weights.set(  NslFillRows.eval(weights,weighttopo));//fill all rows the same
	        stm.set(  NslFillRows.eval(stm,stmtopo));
	}
	if ((direction==3)||(direction==4))
	{
		weights.set(  NslFillColumns.eval(weights,weighttopo));//fill all columns the same
		stm.set(  NslFillColumns.eval(stm,stmtopo));
	}
 	if (system.debug>=26) 
	{
		system.nslPrintln("STM: initRun: direction  :"+direction );
		system.nslPrintln("STM: initRun: stmtopo");
		system.nslPrintln(stmtopo);
		system.nslPrintln("STM: initRun: stm");
		system.nslPrintln(stm);
		system.nslPrintln("STM: initRun: weights:");
		system.nslPrintln(weights);
	}
}
public void makeConn(){
}

	/******************************************************/
	/*                                                    */
	/* Generated by nslc.src.NslCompiler. Do not edit these lines! */
	/*                                                    */
	/******************************************************/

	/* Constructor and related methods */
	/* makeinst() declared variables */

	/* Formal parameters */
	int stdsz;
	int direction;

	/* Temporary variables */
		NslFloat0 __tempSTM0 = new NslFloat0();
		NslFloat0 __tempSTM1 = new NslFloat0();
		NslFloat0 __tempSTM2 = new NslFloat0();
		NslFloat0 __tempSTM3 = new NslFloat0();
		NslFloat0 __tempSTM4 = new NslFloat0();
		NslFloat0 __tempSTM5 = new NslFloat0();
		NslFloat0 __tempSTM6 = new NslFloat0();
		NslFloat0 __tempSTM7 = new NslFloat0();
		NslFloat0 __tempSTM8 = new NslFloat0();
		NslFloat0 __tempSTM9 = new NslFloat0();
		NslFloat0 __tempSTM10 = new NslFloat0();
		NslFloat0 __tempSTM11 = new NslFloat0();
		NslFloat0 __tempSTM12 = new NslFloat0();
		NslFloat0 __tempSTM13 = new NslFloat0();
		NslFloat0 __tempSTM14 = new NslFloat0();
		NslFloat0 __tempSTM15 = new NslFloat0();

	/* GENERIC CONSTRUCTOR: */
	public STM(String nslName, NslModule nslParent, int stdsz, int direction)
{
		super(nslName, nslParent);
		this.stdsz=stdsz;
		this.direction=direction;
		initSys();
		makeInstSTM(nslName, nslParent, stdsz, direction);
	}

	public void makeInstSTM(String nslName, NslModule nslParent, int stdsz, int direction)
{ 
		Object[] nslArgs=new Object[]{stdsz, direction};
		callFromConstructorTop(nslArgs);
		stm = new NslDoutFloat2("stm", this, stdsz, stdsz);
		weights = new NslDoutFloat2("weights", this, stdsz, stdsz);
		stm_k1 = new NslFloat0("stm_k1", this);
		weighttopo = new NslFloat1("weighttopo", this, stdsz);
		stmtopo = new NslFloat1("stmtopo", this, stdsz);
		callFromConstructorBottom();
	}

	/******************************************************/
	/*                                                    */
	/* End of automatic declaration statements.           */
	/*                                                    */
	/******************************************************/


}//end STM

