/** 
Module ThMEDlcn - part of Thalamus
*/
package CrowleyModel.ThMEDlcn.v1_1_1.src;

/*********************************/
/*                               */
/*   Importing all Nsl classes   */
/*                               */
/*********************************/

import nslj.src.system.*;
import nslj.src.cmd.*;
import nslj.src.lang.*;
import nslj.src.math.*;
import nslj.src.display.*;
import nslj.src.display.j3d.*;

/*********************************/

public class ThMEDlcn extends NslModule{

//NSL Version: 3_0_n
//Sif Version: 9
//libNickName: CrowleyModel
//moduleName:  ThMEDlcn
//versionName: 1_1_1
//floatSubModules: true


//variables 
public  NslDinDouble2 RNMEDinh_in; // 
public  NslDoutDouble2 ThMEDlcn_out; // 
private double Thmedlcntm; // 
private double ThmedlcnTONIC; // 
private double ThmedlcnK; // 
private double ThMEDlcnsigma1; // 
private double ThMEDlcnsigma2; // 
private double ThMEDlcnsigma3; // 
private double ThMEDlcnsigma4; // 
private  NslDouble2 Thmedlcn; // 

//methods 
public void initRun(){
    Thmedlcn.set(  0);
    ThMEDlcn_out.set(  0);

     Thmedlcntm=0.006;
     ThmedlcnTONIC=10; ThmedlcnK=1;
     ThMEDlcnsigma1=-10;
     ThMEDlcnsigma2=10;
     ThMEDlcnsigma3=0;
     ThMEDlcnsigma4=10;
}

public void simRun(){
	  /* <Q> RNMEDinh_in */
      // System.err.println("@@@@ ThMEDlcn simRun entered @@@@");
    Thmedlcn.set(system.nsldiff.eval(Thmedlcn,Thmedlcntm,__tempThMEDlcn3.setReference(NslSub.eval(__tempThMEDlcn3.get(), __tempThMEDlcn2.setReference(NslAdd.eval(__tempThMEDlcn2.get(), __tempThMEDlcn0.setReference(NslSub.eval(__tempThMEDlcn0.get(), 0, Thmedlcn)), ThmedlcnTONIC)), (__tempThMEDlcn1.setReference(NslElemMult.eval(__tempThMEDlcn1.get(), ThmedlcnK, RNMEDinh_in)))))));

    ThMEDlcn_out.set(Nsl2Sigmoid.eval(Thmedlcn,ThMEDlcnsigma1,
                            ThMEDlcnsigma2,
                            ThMEDlcnsigma3,
                            ThMEDlcnsigma4));
  }
public void makeConn(){
}

	/******************************************************/
	/*                                                    */
	/* Generated by nslc.src.NslCompiler. Do not edit these lines! */
	/*                                                    */
	/******************************************************/

	/* Constructor and related methods */
	/* makeinst() declared variables */

	/* Formal parameters */
	int array_size;

	/* Temporary variables */
		NslDouble2 __tempThMEDlcn0 = new NslDouble2(1, 1);
		NslDouble2 __tempThMEDlcn1 = new NslDouble2(1, 1);
		NslDouble2 __tempThMEDlcn2 = new NslDouble2(1, 1);
		NslDouble2 __tempThMEDlcn3 = new NslDouble2(1, 1);

	/* GENERIC CONSTRUCTOR: */
	public ThMEDlcn(String nslName, NslModule nslParent, int array_size)
{
		super(nslName, nslParent);
		this.array_size=array_size;
		initSys();
		makeInstThMEDlcn(nslName, nslParent, array_size);
	}

	public void makeInstThMEDlcn(String nslName, NslModule nslParent, int array_size)
{ 
		Object[] nslArgs=new Object[]{array_size};
		callFromConstructorTop(nslArgs);
		RNMEDinh_in = new NslDinDouble2("RNMEDinh_in", this, array_size, array_size);
		ThMEDlcn_out = new NslDoutDouble2("ThMEDlcn_out", this, array_size, array_size);
		Thmedlcn = new NslDouble2("Thmedlcn", this, array_size, array_size);
		callFromConstructorBottom();
	}

	/******************************************************/
	/*                                                    */
	/* End of automatic declaration statements.           */
	/*                                                    */
	/******************************************************/


}//end ThMEDlcn

