package MaxSelectorModel.Ulayer.v1_1_1.src;

/*********************************/
/*                               */
/*   Importing all Nsl classes   */
/*                               */
/*********************************/

import nslj.src.system.*;
import nslj.src.cmd.*;
import nslj.src.lang.*;
import nslj.src.math.*;
import nslj.src.display.*;
import nslj.src.display.j3d.*;

/*********************************/

public class Ulayer extends NslModule{

//NSL Version: 3_0_n
//Sif Version: 9
//libNickName: MaxSelectorModel
//moduleName:  Ulayer
//versionName: 1_1_1
//floatSubModules: true


//variables 
public  NslDinDouble1 s_in; // 
public  NslDinDouble0 v_in; // 
public  NslDoutDouble1 up; // 
public  NslDoutDouble1 uf; // 
private double w1; // 
private double w2; // 
private NslDouble0 hu; // 
private double k; // 
private double tau; // 

//methods 
public void initModule() 
{
	hu.nslSetAccess('W');
	uf.set(0);
	up.set(0);
	tau = 1.0;
	w1= 1.0;
	w2= 1.0;
	hu.set( 0.1);
	k= 0.1;
}

public void simRun() 
{
	up.set(  system.nsldiff.eval(up, tau, __tempMaxSelectorModel_Ulayer_v1_1_1_src_Ulayer6.setReference(NslAdd.eval(__tempMaxSelectorModel_Ulayer_v1_1_1_src_Ulayer6.get(), __tempMaxSelectorModel_Ulayer_v1_1_1_src_Ulayer5.setReference(NslSub.eval(__tempMaxSelectorModel_Ulayer_v1_1_1_src_Ulayer5.get(), __tempMaxSelectorModel_Ulayer_v1_1_1_src_Ulayer4.setReference(NslSub.eval(__tempMaxSelectorModel_Ulayer_v1_1_1_src_Ulayer4.get(), __tempMaxSelectorModel_Ulayer_v1_1_1_src_Ulayer3.setReference(NslAdd.eval(__tempMaxSelectorModel_Ulayer_v1_1_1_src_Ulayer3.get(), __tempMaxSelectorModel_Ulayer_v1_1_1_src_Ulayer0.setReference(NslSub.eval(__tempMaxSelectorModel_Ulayer_v1_1_1_src_Ulayer0.get(), 0, up)), __tempMaxSelectorModel_Ulayer_v1_1_1_src_Ulayer1.setReference(NslElemMult.eval(__tempMaxSelectorModel_Ulayer_v1_1_1_src_Ulayer1.get(), w1, uf)))), __tempMaxSelectorModel_Ulayer_v1_1_1_src_Ulayer2.setReference(w2*v_in.get()))), hu)), s_in)) ));
	uf.set(  NslStep.eval(up,k,0,1.0));
}
public void makeConn(){
}

	/******************************************************/
	/*                                                    */
	/* Generated by nslc.src.NslCompiler. Do not edit these lines! */
	/*                                                    */
	/******************************************************/

	/* Constructor and related methods */
	/* makeinst() declared variables */

	/* Formal parameters */
	int size;

	/* Temporary variables */
		NslDouble1 __tempMaxSelectorModel_Ulayer_v1_1_1_src_Ulayer0 = new NslDouble1(1);
		NslDouble1 __tempMaxSelectorModel_Ulayer_v1_1_1_src_Ulayer1 = new NslDouble1(1);
		NslDouble0 __tempMaxSelectorModel_Ulayer_v1_1_1_src_Ulayer2 = new NslDouble0();
		NslDouble1 __tempMaxSelectorModel_Ulayer_v1_1_1_src_Ulayer3 = new NslDouble1(1);
		NslDouble1 __tempMaxSelectorModel_Ulayer_v1_1_1_src_Ulayer4 = new NslDouble1(1);
		NslDouble1 __tempMaxSelectorModel_Ulayer_v1_1_1_src_Ulayer5 = new NslDouble1(1);
		NslDouble1 __tempMaxSelectorModel_Ulayer_v1_1_1_src_Ulayer6 = new NslDouble1(1);

	/* GENERIC CONSTRUCTOR: */
	public Ulayer(String nslName, NslModule nslParent, int size)
{
		super(nslName, nslParent);
		this.size=size;
		initSys();
		makeInstUlayer(nslName, nslParent, size);
	}

	public void makeInstUlayer(String nslName, NslModule nslParent, int size)
{ 
		Object[] nslArgs=new Object[]{size};
		callFromConstructorTop(nslArgs);
		s_in = new NslDinDouble1("s_in", this, size);
		v_in = new NslDinDouble0("v_in", this);
		up = new NslDoutDouble1("up", this, size);
		uf = new NslDoutDouble1("uf", this, size);
		hu = new NslDouble0("hu", this);
		callFromConstructorBottom();
	}

	/******************************************************/
	/*                                                    */
	/* End of automatic declaration statements.           */
	/*                                                    */
	/******************************************************/


}//end Ulayer

