package MaxSelectorModelMatlab.MaxSelector.v1_1_1.src;
import MaxSelectorModelMatlab.MUlayer.v1_1_1.src.*;
import MaxSelectorModelMatlab.MVlayer.v1_1_1.src.*;

/*********************************/
/*                               */
/*   Importing all Nsl classes   */
/*                               */
/*********************************/

import nslj.src.system.*;
import nslj.src.cmd.*;
import nslj.src.lang.*;
import nslj.src.math.*;
import nslj.src.display.*;
import nslj.src.display.j3d.*;

/*********************************/

public class MaxSelector extends NslModule{

//NSL Version: 3_0_n
//Sif Version: 9
//libNickName: MaxSelectorModelMatlab
//moduleName:  MaxSelector
//versionName: 1_1_1
//floatSubModules: true


//variables 
public  NslDinDouble1 in; // 
public  NslDoutDouble1 out; // 
public  NslDoutDouble1 up_out; // 
public  MUlayer ul; // 
public  MVlayer vl; // 

//methods 

public void makeConn(){
    nslConnect(in,ul.s_in);
    nslConnect(ul.uf,out);
    nslConnect(ul.uf,vl.u_in);
    nslConnect(ul.up,up_out);
    nslConnect(vl.vf,ul.v_in);
}

	/******************************************************/
	/*                                                    */
	/* Generated by nslc.src.NslCompiler. Do not edit these lines! */
	/*                                                    */
	/******************************************************/

	/* Constructor and related methods */
	/* makeinst() declared variables */

	/* Formal parameters */
	int size;

	/* Temporary variables */

	/* GENERIC CONSTRUCTOR: */
	public MaxSelector(String nslName, NslModule nslParent, int size)
{
		super(nslName, nslParent);
		this.size=size;
		initSys();
		makeInstMaxSelector(nslName, nslParent, size);
	}

	public void makeInstMaxSelector(String nslName, NslModule nslParent, int size)
{ 
		Object[] nslArgs=new Object[]{size};
		callFromConstructorTop(nslArgs);
		in = new NslDinDouble1("in", this, size);
		out = new NslDoutDouble1("out", this, size);
		up_out = new NslDoutDouble1("up_out", this, size);
		ul = new MUlayer("ul", this, size);
		vl = new MVlayer("vl", this, size);
		callFromConstructorBottom();
	}

	/******************************************************/
	/*                                                    */
	/* End of automatic declaration statements.           */
	/*                                                    */
	/******************************************************/


}//end MaxSelector

