package DomineyModel.Caudate.v1_1_1.src;

/*********************************/
/*                               */
/*   Importing all Nsl classes   */
/*                               */
/*********************************/

import nslj.src.system.*;
import nslj.src.cmd.*;
import nslj.src.lang.*;
import nslj.src.math.*;
import nslj.src.display.*;
import nslj.src.display.j3d.*;

/*********************************/

public class Caudate extends NslModule{

//NSL Version: 3_0_n
//Sif Version: 9
//libNickName: DomineyModel
//moduleName:  Caudate
//versionName: 1_1_1
//floatSubModules: true


//variables 
public  NslDinFloat2 fefmem; // 
public  NslDinFloat2 fefsac; // 
public  NslDoutFloat2 cdsac; // 
public  NslDoutFloat2 cdmem; // 
private NslFloat0 cdmemPot_tm; // 
private NslFloat0 cdsacPot_tm; // 
private NslFloat0 cdmemPot_k1; // 
private NslFloat0 cdsacPot_k1; // 
private NslFloat0 cdmem_x1; // 
private NslFloat0 cdmem_x2; // 
private NslFloat0 cdmem_y1; // 
private NslFloat0 cdmem_y2; // 
private NslFloat0 cdsac_x1; // 
private NslFloat0 cdsac_x2; // 
private NslFloat0 cdsac_y1; // 
private NslFloat0 cdsac_y2; // 
private  NslFloat2 cdmemPot; // 
private  NslFloat2 cdsacPot; // 

//methods 
public void initRun() 
{
	cdmem.set(0);
	cdsac.set(0);
	cdmemPot_tm.set( .01) ;
	cdsacPot_tm.set(  .008);
	cdmemPot_k1.set( 1) ;
	cdsacPot_k1.set(  1);	
	cdmem_x1.set(50) ;
	cdmem_x2.set(  90);
	cdmem_y1.set( 0) ;
	cdmem_y2.set(60)  ;
	cdsac_x1.set(  0);
	cdsac_x2.set( 50) ;
	cdsac_y1.set(  0);
	cdsac_y2.set( 60) ;	
}

public void simRun() 
{
	cdmemPot.set(system.nsldiff.eval(cdmemPot,cdmemPot_tm, __tempCaudate2.setReference(NslAdd.eval(__tempCaudate2.get(), __tempCaudate0.setReference(NslSub.eval(__tempCaudate0.get(), 0, cdmemPot)), __tempCaudate1.setReference(NslElemMult.eval(__tempCaudate1.get(), cdmemPot_k1, fefmem))))));
	cdsacPot.set(system.nsldiff.eval(cdsacPot,cdsacPot_tm,__tempCaudate5.setReference(NslAdd.eval(__tempCaudate5.get(), __tempCaudate3.setReference(NslSub.eval(__tempCaudate3.get(), 0, cdsacPot)), __tempCaudate4.setReference(NslElemMult.eval(__tempCaudate4.get(), cdsacPot_k1, fefsac))))));
	cdmem.set(  NslSigmoid.eval(cdmemPot,cdmem_x1,cdmem_x2,cdmem_y1,cdmem_y2));
	cdsac.set(  NslSigmoid.eval(cdsacPot,cdsac_x1,cdsac_x2,cdsac_y1,cdsac_y2));

	if (system.debug>22) 
	{
		system.nslPrintln("Caudate: cdmem");
		system.nslPrintln( cdmem);
		system.nslPrintln("Caudate: cdsac");
		system.nslPrintln(cdsac);

	}
}
public void makeConn(){
}

	/******************************************************/
	/*                                                    */
	/* Generated by nslc.src.NslCompiler. Do not edit these lines! */
	/*                                                    */
	/******************************************************/

	/* Constructor and related methods */
	/* makeinst() declared variables */

	/* Formal parameters */
	int stdsz;

	/* Temporary variables */
		NslFloat2 __tempCaudate0 = new NslFloat2(1, 1);
		NslFloat2 __tempCaudate1 = new NslFloat2(1, 1);
		NslFloat2 __tempCaudate2 = new NslFloat2(1, 1);
		NslFloat2 __tempCaudate3 = new NslFloat2(1, 1);
		NslFloat2 __tempCaudate4 = new NslFloat2(1, 1);
		NslFloat2 __tempCaudate5 = new NslFloat2(1, 1);

	/* GENERIC CONSTRUCTOR: */
	public Caudate(String nslName, NslModule nslParent, int stdsz)
{
		super(nslName, nslParent);
		this.stdsz=stdsz;
		initSys();
		makeInstCaudate(nslName, nslParent, stdsz);
	}

	public void makeInstCaudate(String nslName, NslModule nslParent, int stdsz)
{ 
		Object[] nslArgs=new Object[]{stdsz};
		callFromConstructorTop(nslArgs);
		fefmem = new NslDinFloat2("fefmem", this, stdsz, stdsz);
		fefsac = new NslDinFloat2("fefsac", this, stdsz, stdsz);
		cdsac = new NslDoutFloat2("cdsac", this, stdsz, stdsz);
		cdmem = new NslDoutFloat2("cdmem", this, stdsz, stdsz);
		cdmemPot_tm = new NslFloat0("cdmemPot_tm", this);
		cdsacPot_tm = new NslFloat0("cdsacPot_tm", this);
		cdmemPot_k1 = new NslFloat0("cdmemPot_k1", this);
		cdsacPot_k1 = new NslFloat0("cdsacPot_k1", this);
		cdmem_x1 = new NslFloat0("cdmem_x1", this);
		cdmem_x2 = new NslFloat0("cdmem_x2", this);
		cdmem_y1 = new NslFloat0("cdmem_y1", this);
		cdmem_y2 = new NslFloat0("cdmem_y2", this);
		cdsac_x1 = new NslFloat0("cdsac_x1", this);
		cdsac_x2 = new NslFloat0("cdsac_x2", this);
		cdsac_y1 = new NslFloat0("cdsac_y1", this);
		cdsac_y2 = new NslFloat0("cdsac_y2", this);
		cdmemPot = new NslFloat2("cdmemPot", this, stdsz, stdsz);
		cdsacPot = new NslFloat2("cdsacPot", this, stdsz, stdsz);
		callFromConstructorBottom();
	}

	/******************************************************/
	/*                                                    */
	/* End of automatic declaration statements.           */
	/*                                                    */
	/******************************************************/


}//end Caudate

