package MaxSelectorModel.MaxSelectorStimulus.v1_1_1.src;

/*********************************/
/*                               */
/*   Importing all Nsl classes   */
/*                               */
/*********************************/

import nslj.src.system.*;
import nslj.src.cmd.*;
import nslj.src.lang.*;
import nslj.src.math.*;
import nslj.src.display.*;
import nslj.src.display.j3d.*;

/*********************************/

public class MaxSelectorStimulus extends NslJavaModule{

//NSL Version: 3_0_n
//Sif Version: 9
//libNickName: MaxSelectorModel
//moduleName:  MaxSelectorStimulus
//versionName: 1_1_1
//floatSubModules: true


//variables 
public  NslDoutDouble1 s_out; // 

//methods 
public void initModule() 
{
	s_out.nslSetAccess('W');
	s_out.set(0);
	s_out.set(1, 0.5);
	s_out.set(3, 1.0);
}
public void makeConn(){
}

	/******************************************************/
	/*                                                    */
	/* Generated by nslc.src.NslCompiler. Do not edit these lines! */
	/*                                                    */
	/******************************************************/

	/* Constructor and related methods */
	/* makeinst() declared variables */

	/* Formal parameters */
	int size;

	/* Temporary variables */

	/* GENERIC CONSTRUCTOR: */
	public MaxSelectorStimulus(String nslName, NslModule nslParent, int size)
{
		super(nslName, nslParent);
		this.size=size;
		initSys();
		makeInstMaxSelectorStimulus(nslName, nslParent, size);
	}

	public void makeInstMaxSelectorStimulus(String nslName, NslModule nslParent, int size)
{ 
		Object[] nslArgs=new Object[]{size};
		callFromConstructorTop(nslArgs);
		s_out = new NslDoutDouble1("s_out", this, size);
		callFromConstructorBottom();
	}

	/******************************************************/
	/*                                                    */
	/* End of automatic declaration statements.           */
	/*                                                    */
	/******************************************************/


}//end MaxSelectorStimulus

