package DomineyModel.Retina.v1_1_1.src;
import DomineyModel.DomineyLib.v1_1_1.src.*;

/*********************************/
/*                               */
/*   Importing all Nsl classes   */
/*                               */
/*********************************/

import nslj.src.system.*;
import nslj.src.cmd.*;
import nslj.src.lang.*;
import nslj.src.math.*;
import nslj.src.display.*;
import nslj.src.display.j3d.*;

/*********************************/

public class Retina extends NslModule{

//NSL Version: 3_0_n
//Sif Version: 9
//libNickName: DomineyModel
//moduleName:  Retina
//versionName: 1_1_1
//floatSubModules: true


//variables 
public  NslDinFloat2 saccademask; // 
public  NslDinFloat2 visualinput; // 
public  NslDinFloat0 horizontalTheta; // 
public  NslDinFloat0 verticalTheta; // 
public  NslDoutFloat2 retina; // 
private NslFloat0 retinaPot_tm; // 
private  NslFloat2 retinaPot; // 
private  NslFloat2 retinaPot1; // 
public  DomineyLib domineyLib; // 

//methods 
public void initRun() 
{
	retina.set(0);
	retinaPot.set(0);
	retinaPot1.set(0);
	retinaPot_tm.set(.006);
}

public void simRun()
{
	retinaPot1.set(  domineyLib.eyeMove(visualinput,horizontalTheta,verticalTheta,stdsz,bigsz));
	retinaPot.set(system.nsldiff.eval(retinaPot,retinaPot_tm, __tempRetina1.setReference(NslAdd.eval(__tempRetina1.get(), __tempRetina0.setReference(NslSub.eval(__tempRetina0.get(), 0, retinaPot)), retinaPot1)) ));
	retina.set(  __tempRetina2.setReference(NslElemMult.eval(__tempRetina2.get(), saccademask, retinaPot)));

	if (system.debug>=15) 
	{
		system.nslPrintln("debug: Retina:retinaPot1 ");
		system.nslPrintln(retinaPot1);
		system.nslPrintln("debug: Retina:retinaPot ");
		system.nslPrintln(retinaPot);
		system.nslPrintln("debug: Retina:retina ");
		system.nslPrintln(retina);
	}
}
public void makeConn(){
}

	/******************************************************/
	/*                                                    */
	/* Generated by nslc.src.NslCompiler. Do not edit these lines! */
	/*                                                    */
	/******************************************************/

	/* Constructor and related methods */
	/* makeinst() declared variables */

	/* Formal parameters */
	int stdsz;
	int bigsz;

	/* Temporary variables */
		NslFloat2 __tempRetina0 = new NslFloat2(1, 1);
		NslFloat2 __tempRetina1 = new NslFloat2(1, 1);
		NslFloat2 __tempRetina2 = new NslFloat2(1, 1);

	/* GENERIC CONSTRUCTOR: */
	public Retina(String nslName, NslModule nslParent, int stdsz, int bigsz)
{
		super(nslName, nslParent);
		this.stdsz=stdsz;
		this.bigsz=bigsz;
		initSys();
		makeInstRetina(nslName, nslParent, stdsz, bigsz);
	}

	public void makeInstRetina(String nslName, NslModule nslParent, int stdsz, int bigsz)
{ 
		Object[] nslArgs=new Object[]{stdsz, bigsz};
		callFromConstructorTop(nslArgs);
		saccademask = new NslDinFloat2("saccademask", this, stdsz, stdsz);
		visualinput = new NslDinFloat2("visualinput", this, bigsz, bigsz);
		horizontalTheta = new NslDinFloat0("horizontalTheta", this);
		verticalTheta = new NslDinFloat0("verticalTheta", this);
		retina = new NslDoutFloat2("retina", this, stdsz, stdsz);
		retinaPot_tm = new NslFloat0("retinaPot_tm", this);
		retinaPot = new NslFloat2("retinaPot", this, stdsz, stdsz);
		retinaPot1 = new NslFloat2("retinaPot1", this, stdsz, stdsz);
		domineyLib = new DomineyLib("domineyLib", this);
		callFromConstructorBottom();
	}

	/******************************************************/
	/*                                                    */
	/* End of automatic declaration statements.           */
	/*                                                    */
	/******************************************************/


}//end Retina

