/** 
 CDmedtan class
 Represents the Caudate Tonically Active Cells Layer
 see     CDmedtan
 version 0.1 96-11-19
 author  Michael Crowley
 -var private SNCdop_in - input coming from SNC module (of type NslDouble2)
 -var private CDmedinh_in - input coming from CDmedinh module (of type NslDouble2)
 -var private CDmedtan_out - output going to CDmedburst module (of type NslDouble2)
*/
package CrowleyModel.CDmedtan.v1_1_1.src;

/*********************************/
/*                               */
/*   Importing all Nsl classes   */
/*                               */
/*********************************/

import nslj.src.system.*;
import nslj.src.cmd.*;
import nslj.src.lang.*;
import nslj.src.math.*;
import nslj.src.display.*;
import nslj.src.display.j3d.*;

/*********************************/

public class CDmedtan extends NslModule{

//NSL Version: 3_0_n
//Sif Version: 9
//libNickName: CrowleyModel
//moduleName:  CDmedtan
//versionName: 1_1_1
//floatSubModules: true


//variables 
public  NslDinDouble2 SNCdop_in; // 
public  NslDinDouble2 CDmedinh_in; // 
public  NslDoutDouble2 CDmedtan_out; // 
private double cdmedtantm; // 
private double cdmedtanTONIC; // 
private double CDSNCdopK; // 
private double CDltsigma1; // 
private double CDltsigma2; // 
private double CDltsigma3; // 
private double CDltsigma4; // 
private  NslDouble2 cdmedtan; // 

//methods 
public void initRun () 
{
	CDmedtan_out.set(0);

	cdmedtantm = 0.01;
	cdmedtanTONIC = 10;
	CDSNCdopK = 0.5;
	CDltsigma1 = 0;
	CDltsigma2 = 10;
	CDltsigma3 = 0;
	CDltsigma4 = 10;
}

public void simRun () 
{
	// System.err.println("@@@@ CDmedtanh simRun entered @@@@");
	cdmedtan.set(  system.nsldiff.eval(cdmedtan,cdmedtantm, 
                              __tempCDmedtan3.setReference(NslSub.eval(__tempCDmedtan3.get(), __tempCDmedtan2.setReference(NslSub.eval(__tempCDmedtan2.get(), __tempCDmedtan1.setReference(NslAdd.eval(__tempCDmedtan1.get(), __tempCDmedtan0.setReference(NslSub.eval(__tempCDmedtan0.get(), 0, cdmedtan)), cdmedtanTONIC)), CDmedinh_in)), (CDSNCdopK*NslMaxValue.eval(SNCdop_in))))));
	CDmedtan_out.set(  Nsl2Sigmoid.eval( cdmedtan,CDltsigma1, CDltsigma2,
                                     CDltsigma3, CDltsigma4)); 
}
public void makeConn(){
}

	/******************************************************/
	/*                                                    */
	/* Generated by nslc.src.NslCompiler. Do not edit these lines! */
	/*                                                    */
	/******************************************************/

	/* Constructor and related methods */
	/* makeinst() declared variables */

	/* Formal parameters */
	int CorticalArraySize;
	int StriatalArraySize;

	/* Temporary variables */
		NslDouble2 __tempCDmedtan0 = new NslDouble2(1, 1);
		NslDouble2 __tempCDmedtan1 = new NslDouble2(1, 1);
		NslDouble2 __tempCDmedtan2 = new NslDouble2(1, 1);
		NslDouble2 __tempCDmedtan3 = new NslDouble2(1, 1);

	/* GENERIC CONSTRUCTOR: */
	public CDmedtan(String nslName, NslModule nslParent, int CorticalArraySize, int StriatalArraySize)
{
		super(nslName, nslParent);
		this.CorticalArraySize=CorticalArraySize;
		this.StriatalArraySize=StriatalArraySize;
		initSys();
		makeInstCDmedtan(nslName, nslParent, CorticalArraySize, StriatalArraySize);
	}

	public void makeInstCDmedtan(String nslName, NslModule nslParent, int CorticalArraySize, int StriatalArraySize)
{ 
		Object[] nslArgs=new Object[]{CorticalArraySize, StriatalArraySize};
		callFromConstructorTop(nslArgs);
		SNCdop_in = new NslDinDouble2("SNCdop_in", this, StriatalArraySize, StriatalArraySize);
		CDmedinh_in = new NslDinDouble2("CDmedinh_in", this, StriatalArraySize, StriatalArraySize);
		CDmedtan_out = new NslDoutDouble2("CDmedtan_out", this, StriatalArraySize, StriatalArraySize);
		cdmedtan = new NslDouble2("cdmedtan", this, StriatalArraySize, StriatalArraySize);
		callFromConstructorBottom();
	}

	/******************************************************/
	/*                                                    */
	/* End of automatic declaration statements.           */
	/*                                                    */
	/******************************************************/


}//end CDmedtan

