package MaxSelectorModelMatlab.MaxSelectorModel.v1_1_1.src;
import MaxSelectorModelMatlab.MaxSelectorStimulus.v1_1_1.src.*;
import MaxSelectorModelMatlab.MaxSelector.v1_1_1.src.*;

/*********************************/
/*                               */
/*   Importing all Nsl classes   */
/*                               */
/*********************************/

import nslj.src.system.*;
import nslj.src.cmd.*;
import nslj.src.lang.*;
import nslj.src.math.*;
import nslj.src.display.*;
import nslj.src.display.j3d.*;

/*********************************/

public class MaxSelectorModel extends NslModel{

//NSL Version: 3_0_n
//Sif Version: 9
//libNickName: MaxSelectorModelMatlab
//moduleName:  MaxSelectorModel
//versionName: 1_1_1
//floatSubModules: true


//variables 
public  MaxSelectorStimulus stimulus; // 
public  MaxSelector maxselector; // 
private int size=10; // 

//methods 
public void initSys() 
{
	system.setEndTime(10.0);
	system.setRunDelta(0.1);
}

public void initModule()
{
	nslSetRunDelta(0.1);
	nslAddAreaCanvas("output", "s_out", stimulus.s_out,0.0,1.0);
	nslAddTemporalCanvas("output", "up_out", maxselector.up_out,-2,2,NslColor.getColor("BLACK"));
	nslAddAreaCanvas("output", "out", maxselector.out,0.0,1.0);
}
public void makeConn(){
    nslConnect(stimulus.s_out,maxselector.in);
}

	/******************************************************/
	/*                                                    */
	/* Generated by nslc.src.NslCompiler. Do not edit these lines! */
	/*                                                    */
	/******************************************************/

	/* Constructor and related methods */
	/* makeinst() declared variables */

	/* EMPTY CONSTRUCTOR: Called only for the top level module */
	public MaxSelectorModel() {
		super("maxSelectorModel",(NslModel)null);
		initSys();
		makeInstMaxSelectorModel("maxSelectorModel",null);
	}

	/* Formal parameters */

	/* Temporary variables */

	/* GENERIC CONSTRUCTOR: */
	public MaxSelectorModel(String nslName, NslModule nslParent)
{
		super(nslName, nslParent);
		initSys();
		makeInstMaxSelectorModel(nslName, nslParent);
	}

	public void makeInstMaxSelectorModel(String nslName, NslModule nslParent)
{ 
		Object[] nslArgs=new Object[]{};
		callFromConstructorTop(nslArgs);
		stimulus = new MaxSelectorStimulus("stimulus", this, size);
		maxselector = new MaxSelector("maxselector", this, size);
		callFromConstructorBottom();
	}

	/******************************************************/
	/*                                                    */
	/* End of automatic declaration statements.           */
	/*                                                    */
	/******************************************************/


}//end MaxSelectorModel

