/** 
Module ThLIPmem - parth of the Thalamus
*/
package CrowleyModel.ThLIPmem.v1_1_1.src;

/*********************************/
/*                               */
/*   Importing all Nsl classes   */
/*                               */
/*********************************/

import nslj.src.system.*;
import nslj.src.cmd.*;
import nslj.src.lang.*;
import nslj.src.math.*;
import nslj.src.display.*;
import nslj.src.display.j3d.*;

/*********************************/

public class ThLIPmem extends NslModule{

//NSL Version: 3_0_n
//Sif Version: 9
//libNickName: CrowleyModel
//moduleName:  ThLIPmem
//versionName: 1_1_1
//floatSubModules: true


//variables 
public  NslDinDouble2 LIPmem_in; // 
public  NslDinDouble2 SNRmedburst_in; // 
public  NslDinDouble2 ThMEDlcn_in; // 
public  NslDoutDouble2 ThLIPmem_out; // 
public  NslDoutDouble2 THNA_out; // 
private double Thlipmemtm; // 
private double ThlipmemK1; // 
private double ThlipmemK2; // 
private double ThlipmemK3; // 
private double ThLIPmemsigma1; // 
private double ThLIPmemsigma2; // 
private double ThLIPmemsigma3; // 
private double ThLIPmemsigma4; // 
private  NslDouble2 Thlipmem; // 
private  NslDouble2 THNewActivation; // 

//methods 
public void initModule(){
   THNewActivation.set((NslDouble2)nslGetValue("crowleyModel.thal1.THNewActivation"));


   //System.out.println("\n\n``````````````````````` THNewActivation:"+THNewActivation+"\n\n");
}

public void initRun(){
     ThLIPmem_out.set(  0);
     Thlipmem.set( 0);

     Thlipmemtm=0.006;
     ThlipmemK1=1.5;
     ThlipmemK2=0.5;
     ThlipmemK3=0.5;
     ThLIPmemsigma1=30;
     ThLIPmemsigma2=65;
     ThLIPmemsigma3=0;
     ThLIPmemsigma4=60;
     THNA_out.set(THNewActivation);
}

public void simRun(){
  /* <Q> LIPmem_in SNRmedburst_in ThMEDlcn_in THNewActivation */

  // System.err.println("@@@@ ThLIPmem simRun entered @@@@");
   THNewActivation.set((NslDouble2)nslGetValue("crowleyModel.thal1.THNewActivation"));

     THNA_out.set(THNewActivation);
//System.err.println("THNEWACT:"+THNewActivation);
    Thlipmem.set(system.nsldiff.eval(Thlipmem,Thlipmemtm,__tempThLIPmem7.setReference(NslAdd.eval(__tempThLIPmem7.get(), __tempThLIPmem6.setReference(NslSub.eval(__tempThLIPmem6.get(), __tempThLIPmem5.setReference(NslSub.eval(__tempThLIPmem5.get(), __tempThLIPmem4.setReference(NslAdd.eval(__tempThLIPmem4.get(), __tempThLIPmem0.setReference(NslSub.eval(__tempThLIPmem0.get(), 0, Thlipmem)), (__tempThLIPmem1.setReference(NslElemMult.eval(__tempThLIPmem1.get(), ThlipmemK1, LIPmem_in))))), (__tempThLIPmem2.setReference(NslElemMult.eval(__tempThLIPmem2.get(), ThlipmemK2, SNRmedburst_in))))), (__tempThLIPmem3.setReference(NslElemMult.eval(__tempThLIPmem3.get(), ThlipmemK3, ThMEDlcn_in))))), THNewActivation))));

   ThLIPmem_out.set(Nsl2Sigmoid.eval(Thlipmem,ThLIPmemsigma1,
                            ThLIPmemsigma2,
                            ThLIPmemsigma3,
                            ThLIPmemsigma4));
  }
public void makeConn(){
}

	/******************************************************/
	/*                                                    */
	/* Generated by nslc.src.NslCompiler. Do not edit these lines! */
	/*                                                    */
	/******************************************************/

	/* Constructor and related methods */
	/* makeinst() declared variables */

	/* Formal parameters */
	int array_size;

	/* Temporary variables */
		NslDouble2 __tempThLIPmem0 = new NslDouble2(1, 1);
		NslDouble2 __tempThLIPmem1 = new NslDouble2(1, 1);
		NslDouble2 __tempThLIPmem2 = new NslDouble2(1, 1);
		NslDouble2 __tempThLIPmem3 = new NslDouble2(1, 1);
		NslDouble2 __tempThLIPmem4 = new NslDouble2(1, 1);
		NslDouble2 __tempThLIPmem5 = new NslDouble2(1, 1);
		NslDouble2 __tempThLIPmem6 = new NslDouble2(1, 1);
		NslDouble2 __tempThLIPmem7 = new NslDouble2(1, 1);

	/* GENERIC CONSTRUCTOR: */
	public ThLIPmem(String nslName, NslModule nslParent, int array_size)
{
		super(nslName, nslParent);
		this.array_size=array_size;
		initSys();
		makeInstThLIPmem(nslName, nslParent, array_size);
	}

	public void makeInstThLIPmem(String nslName, NslModule nslParent, int array_size)
{ 
		Object[] nslArgs=new Object[]{array_size};
		callFromConstructorTop(nslArgs);
		LIPmem_in = new NslDinDouble2("LIPmem_in", this, array_size, array_size);
		SNRmedburst_in = new NslDinDouble2("SNRmedburst_in", this, array_size, array_size);
		ThMEDlcn_in = new NslDinDouble2("ThMEDlcn_in", this, array_size, array_size);
		ThLIPmem_out = new NslDoutDouble2("ThLIPmem_out", this, array_size, array_size);
		THNA_out = new NslDoutDouble2("THNA_out", this, array_size, array_size);
		Thlipmem = new NslDouble2("Thlipmem", this, array_size, array_size);
		THNewActivation = new NslDouble2("THNewActivation", this, array_size, array_size);
		callFromConstructorBottom();
	}

	/******************************************************/
	/*                                                    */
	/* End of automatic declaration statements.           */
	/*                                                    */
	/******************************************************/


}//end ThLIPmem

