package DartModel.IO_layer.v1_1_1.src;

/*********************************/
/*                               */
/*   Importing all Nsl classes   */
/*                               */
/*********************************/

import nslj.src.system.*;
import nslj.src.cmd.*;
import nslj.src.lang.*;
import nslj.src.math.*;
import nslj.src.display.*;
import nslj.src.display.j3d.*;

/*********************************/

public class IO_layer extends NslModule{

//NSL Version: 3_0_n
//Sif Version: 9
//libNickName: DartModel
//moduleName:  IO_layer
//versionName: 1_1_1
//floatSubModules: true


//variables 
public  NslDinDouble1 sens_in; // SENS input
public  NslDinDouble1 nuc_in; // NUC input
public  NslDoutDouble1 io_out; // 
private double f_max=10; // 
private double offset=1.3865; // gives output of 2 for 0 input
private double slope=1; // 
private  NslDouble1 io_mp; // 

//methods 
public void initModule() 
{
	io_out.set(  2.);
}

public void simTrain() 
{
	simRun();
}

public void simRun() 
{
	double nuc_act;

	nuc_act = NslSumRows.eval(nuc_in);
	io_mp.set(    __tempIO_layer0.setReference(NslSub.eval(__tempIO_layer0.get(), sens_in, .01*nuc_act)));
	io_out.set(   __tempIO_layer1 = (NslElemMult.eval(__tempIO_layer1, f_max, NslSigmoid.eval(io_mp,slope,offset))));
}
public void makeConn(){
}

	/******************************************************/
	/*                                                    */
	/* Generated by nslc.src.NslCompiler. Do not edit these lines! */
	/*                                                    */
	/******************************************************/

	/* Constructor and related methods */
	/* makeinst() declared variables */

	/* Formal parameters */

	/* Temporary variables */
		NslDouble1 __tempIO_layer0 = new NslDouble1(1);
		double[] __tempIO_layer1 = new double[1];

	/* GENERIC CONSTRUCTOR: */
	public IO_layer(String nslName, NslModule nslParent)
{
		super(nslName, nslParent);
		initSys();
		makeInstIO_layer(nslName, nslParent);
	}

	public void makeInstIO_layer(String nslName, NslModule nslParent)
{ 
		Object[] nslArgs=new Object[]{};
		callFromConstructorTop(nslArgs);
		sens_in = new NslDinDouble1("sens_in", this, 2);
		nuc_in = new NslDinDouble1("nuc_in", this, 2);
		io_out = new NslDoutDouble1("io_out", this, 2);
		io_mp = new NslDouble1("io_mp", this, 2);
		callFromConstructorBottom();
	}

	/******************************************************/
	/*                                                    */
	/* End of automatic declaration statements.           */
	/*                                                    */
	/******************************************************/


}//end IO_layer

