/** 
 GPElatburst class
 Represents the Globus Pallidus External Burst Cells Layer
 see    GPElatburst
 version 0.1 96-11-19
 author  Michael Crowley
 -var private CDindlatburst_in - input coming from CDlatburst module (of type NslDouble2)
 -var private GPElatburst_out - output going to STNlatburst module (of type NslDouble2)
*/
package CrowleyModel.GPElatburst.v1_1_1.src;

/*********************************/
/*                               */
/*   Importing all Nsl classes   */
/*                               */
/*********************************/

import nslj.src.system.*;
import nslj.src.cmd.*;
import nslj.src.lang.*;
import nslj.src.math.*;
import nslj.src.display.*;
import nslj.src.display.j3d.*;

/*********************************/

public class GPElatburst extends NslModule{

//NSL Version: 3_0_n
//Sif Version: 9
//libNickName: CrowleyModel
//moduleName:  GPElatburst
//versionName: 1_1_1
//floatSubModules: true


//variables 
public  NslDinDouble2 CDindlatburst_in; // 
public  NslDoutDouble2 GPElatburst_out; // 
private double gpelatbursttm; // 
private double GPElatburstTONIC; // 
private double GPElatburstK; // 
private double GPElbsigma1; // 
private double GPElbsigma2; // 
private double GPElbsigma3; // 
private double GPElbsigma4; // 
private  NslDouble2 gpelatburst; // 

//methods 
public void initRun () 
{
	GPElatburst_out.set( 0);

	//System.err.println("GPElatburst:=1=");
	gpelatbursttm = 0.01;
	//System.err.println("GPElatburst:=2=");
	GPElatburstTONIC = 30;
	//System.err.println("GPElatburst:=3=");
	GPElatburstK = 2;
	//System.err.println("GPElatburst:=4=");
	GPElbsigma1 = 0;
	//System.err.println("GPElatburst:=5=");
	GPElbsigma2 = 60;
	//System.err.println("GPElatburst:=6=");
	GPElbsigma3 = 0;
	//System.err.println("GPElatburst:=7=");
	GPElbsigma4 = 60;
	//System.err.println("GPElatburst:=8=");
}

public void simRun () 
{
	// System.err.println("@@@@ GPElatburst simRun entered @@@@");
	gpelatburst.set(  system.nsldiff.eval (gpelatburst,gpelatbursttm, __tempGPElatburst3.setReference(NslSub.eval(__tempGPElatburst3.get(), __tempGPElatburst2.setReference(NslAdd.eval(__tempGPElatburst2.get(), __tempGPElatburst0.setReference(NslSub.eval(__tempGPElatburst0.get(), 0, gpelatburst)), GPElatburstTONIC)), (__tempGPElatburst1.setReference(NslElemMult.eval(__tempGPElatburst1.get(), GPElatburstK, CDindlatburst_in)))))));
	GPElatburst_out.set(  Nsl2Sigmoid.eval (gpelatburst,GPElbsigma1, GPElbsigma2, GPElbsigma3, GPElbsigma4));
}
public void makeConn(){
}

	/******************************************************/
	/*                                                    */
	/* Generated by nslc.src.NslCompiler. Do not edit these lines! */
	/*                                                    */
	/******************************************************/

	/* Constructor and related methods */
	/* makeinst() declared variables */

	/* Formal parameters */
	int CorticalArraySize;

	/* Temporary variables */
		NslDouble2 __tempGPElatburst0 = new NslDouble2(1, 1);
		NslDouble2 __tempGPElatburst1 = new NslDouble2(1, 1);
		NslDouble2 __tempGPElatburst2 = new NslDouble2(1, 1);
		NslDouble2 __tempGPElatburst3 = new NslDouble2(1, 1);

	/* GENERIC CONSTRUCTOR: */
	public GPElatburst(String nslName, NslModule nslParent, int CorticalArraySize)
{
		super(nslName, nslParent);
		this.CorticalArraySize=CorticalArraySize;
		initSys();
		makeInstGPElatburst(nslName, nslParent, CorticalArraySize);
	}

	public void makeInstGPElatburst(String nslName, NslModule nslParent, int CorticalArraySize)
{ 
		Object[] nslArgs=new Object[]{CorticalArraySize};
		callFromConstructorTop(nslArgs);
		CDindlatburst_in = new NslDinDouble2("CDindlatburst_in", this, CorticalArraySize, CorticalArraySize);
		GPElatburst_out = new NslDoutDouble2("GPElatburst_out", this, CorticalArraySize, CorticalArraySize);
		gpelatburst = new NslDouble2("gpelatburst", this, CorticalArraySize, CorticalArraySize);
		callFromConstructorBottom();
	}

	/******************************************************/
	/*                                                    */
	/* End of automatic declaration statements.           */
	/*                                                    */
	/******************************************************/


}//end GPElatburst

