package DomineyModel.Erasure2.v1_1_1.src;

/*********************************/
/*                               */
/*   Importing all Nsl classes   */
/*                               */
/*********************************/

import nslj.src.system.*;
import nslj.src.cmd.*;
import nslj.src.lang.*;
import nslj.src.math.*;
import nslj.src.display.*;
import nslj.src.display.j3d.*;

/*********************************/

public class Erasure2 extends NslModule{

//NSL Version: 3_0_n
//Sif Version: 9
//libNickName: DomineyModel
//moduleName:  Erasure2
//versionName: 1_1_1
//floatSubModules: true


//variables 
public  NslDoutFloat2 erasure2; // 
private int halfStdsz=0; // 
private int oneThirdStdsz=0; // 
private int twoThirdsStdszMin1=0; // 

//methods 
public void initModule() 
{	
	halfStdsz=(int)stdsz/2;  // if stdsz=9, then this is 4
	oneThirdStdsz=(int)stdsz/3;  //if stdsz=9, then this is 3
	twoThirdsStdszMin1=oneThirdStdsz+oneThirdStdsz-1; //if, then 5
}

public void initRun() 
{
	// the following draws a square outlining the fovea
	// with 1 everywhere except the outline which is 0.5
	erasure2.set(1);       // set everything to 1 then set some to 0.5                    
	erasure2.set(oneThirdStdsz, oneThirdStdsz,   .5);
	erasure2.set(oneThirdStdsz, halfStdsz,   0.5); 
	erasure2.set(oneThirdStdsz, twoThirdsStdszMin1,   0.5);

	erasure2.set(halfStdsz, oneThirdStdsz,   0.5);
	erasure2.set(halfStdsz, halfStdsz,   0.5); 
	erasure2.set(halfStdsz, twoThirdsStdszMin1,   0.5);

	erasure2.set(twoThirdsStdszMin1, oneThirdStdsz,   0.5);
	erasure2.set(twoThirdsStdszMin1, halfStdsz,   0.5); 
	erasure2.set(twoThirdsStdszMin1, twoThirdsStdszMin1,   0.5);

	if (system.debug>1) 
	{
		system.nslPrintln("Erasure2:initRun: erasure2");
		system.nslPrintln(erasure2);
	}
}
public void makeConn(){
}

	/******************************************************/
	/*                                                    */
	/* Generated by nslc.src.NslCompiler. Do not edit these lines! */
	/*                                                    */
	/******************************************************/

	/* Constructor and related methods */
	/* makeinst() declared variables */

	/* Formal parameters */
	int stdsz;

	/* Temporary variables */

	/* GENERIC CONSTRUCTOR: */
	public Erasure2(String nslName, NslModule nslParent, int stdsz)
{
		super(nslName, nslParent);
		this.stdsz=stdsz;
		initSys();
		makeInstErasure2(nslName, nslParent, stdsz);
	}

	public void makeInstErasure2(String nslName, NslModule nslParent, int stdsz)
{ 
		Object[] nslArgs=new Object[]{stdsz};
		callFromConstructorTop(nslArgs);
		erasure2 = new NslDoutFloat2("erasure2", this, stdsz, stdsz);
		callFromConstructorBottom();
	}

	/******************************************************/
	/*                                                    */
	/* End of automatic declaration statements.           */
	/*                                                    */
	/******************************************************/


}//end Erasure2

