package DomineyModel.Motor.v1_1_1.src;
import DomineyModel.MLBN.v1_1_1.src.*;
import DomineyModel.EBN.v1_1_1.src.*;
import DomineyModel.Pause.v1_1_1.src.*;
import DomineyModel.TNDelta.v1_1_1.src.*;
import DomineyModel.MN.v1_1_1.src.*;
import DomineyModel.STM.v1_1_1.src.*;

/*********************************/
/*                               */
/*   Importing all Nsl classes   */
/*                               */
/*********************************/

import nslj.src.system.*;
import nslj.src.cmd.*;
import nslj.src.lang.*;
import nslj.src.math.*;
import nslj.src.display.*;
import nslj.src.display.j3d.*;

/*********************************/

public class Motor extends NslModule{

//NSL Version: 3_0_n
//Sif Version: 9
//libNickName: DomineyModel
//moduleName:  Motor
//versionName: 1_1_1
//floatSubModules: true


//variables 
public  NslDinFloat2 supcol; // 
public  NslDinFloat2 llbn; // 
public  NslDinFloat2 fefsac; // 
public  NslDinFloat0 tn; // 
public  NslDoutFloat0 ebn; // 
public  NslDoutFloat0 fefgate; // 
public  NslDoutFloat0 mn; // 
public  NslDoutFloat0 tnDelta; // 
public  MLBN mlbnl; // 
public  EBN ebnl; // 
public  Pause pausel; // 
public  TNDelta tnDeltal; // 
public  MN mnl; // 
public  STM stml; // 

//methods 
public void initModule() 
{
	if (system.debug>=6) 
	{
		system.nslPrintln("debug:Motor:initModule:direction "+direction);
	}

}

public void initRun() 
{
	if (system.debug>=6) 
	{
		system.nslPrintln("debug:Motor:initRun:direction "+direction);
	}
}
public void makeConn(){
    nslConnect(llbn,mlbnl.llbn);
    nslConnect(supcol,pausel.supcol);
    nslConnect(fefsac,pausel.fefsac);
    nslConnect(fefsac,tnDeltal.fefsac);
    nslConnect(tn,mnl.tn);
    nslConnect(tn,tnDeltal.tn);
    nslConnect(mlbnl.mlbn,ebnl.mlbn);
    nslConnect(mlbnl.mlbn,pausel.mlbn);
    nslConnect(mnl.mn,mn);
    nslConnect(stml.stm,mlbnl.stm);
    nslConnect(stml.stm,pausel.stm);
    nslConnect(stml.weights,pausel.weights);
    nslConnect(tnDeltal.fefgate,fefgate);
    nslConnect(tnDeltal.tnDelta,tnDelta);
    nslConnect(pausel.pause,ebnl.pause);
    nslConnect(ebnl.ebn,mnl.ebn);
    nslConnect(ebnl.ebn,ebn);
    nslConnect(ebnl.ebn,pausel.ebn);
}

	/******************************************************/
	/*                                                    */
	/* Generated by nslc.src.NslCompiler. Do not edit these lines! */
	/*                                                    */
	/******************************************************/

	/* Constructor and related methods */
	/* makeinst() declared variables */

	/* Formal parameters */
	int stdsz;
	int direction;

	/* Temporary variables */

	/* GENERIC CONSTRUCTOR: */
	public Motor(String nslName, NslModule nslParent, int stdsz, int direction)
{
		super(nslName, nslParent);
		this.stdsz=stdsz;
		this.direction=direction;
		initSys();
		makeInstMotor(nslName, nslParent, stdsz, direction);
	}

	public void makeInstMotor(String nslName, NslModule nslParent, int stdsz, int direction)
{ 
		Object[] nslArgs=new Object[]{stdsz, direction};
		callFromConstructorTop(nslArgs);
		supcol = new NslDinFloat2("supcol", this, stdsz, stdsz);
		llbn = new NslDinFloat2("llbn", this, stdsz, stdsz);
		fefsac = new NslDinFloat2("fefsac", this, stdsz, stdsz);
		tn = new NslDinFloat0("tn", this);
		ebn = new NslDoutFloat0("ebn", this);
		fefgate = new NslDoutFloat0("fefgate", this);
		mn = new NslDoutFloat0("mn", this);
		tnDelta = new NslDoutFloat0("tnDelta", this);
		mlbnl = new MLBN("mlbnl", this, stdsz);
		ebnl = new EBN("ebnl", this, stdsz);
		pausel = new Pause("pausel", this, stdsz);
		tnDeltal = new TNDelta("tnDeltal", this, stdsz);
		mnl = new MN("mnl", this);
		stml = new STM("stml", this, stdsz, direction);
		callFromConstructorBottom();
	}

	/******************************************************/
	/*                                                    */
	/* End of automatic declaration statements.           */
	/*                                                    */
	/******************************************************/


}//end Motor

