/** 
Module RNMEDinh - part of thalamus
*/
package CrowleyModel.RNMEDinh.v1_1_1.src;

/*********************************/
/*                               */
/*   Importing all Nsl classes   */
/*                               */
/*********************************/

import nslj.src.system.*;
import nslj.src.cmd.*;
import nslj.src.lang.*;
import nslj.src.math.*;
import nslj.src.display.*;
import nslj.src.display.j3d.*;

/*********************************/

public class RNMEDinh extends NslModule{

//NSL Version: 3_0_n
//Sif Version: 9
//libNickName: CrowleyModel
//moduleName:  RNMEDinh
//versionName: 1_1_1
//floatSubModules: true


//variables 
public  NslDinDouble2 SNRmedburst_in; // 
public  NslDoutDouble2 RNMEDinh_out; // 
private  NslDouble2 RNmedinh; // 
private double RNmedinhtm; // 
private double RNmedinhTONIC; // 
private double RNmedinhK; // 
private double RNmedinhsigma1; // 
private double RNmedinhsigma2; // 
private double RNmedinhsigma3; // 
private double RNmedinhsigma4; // 

//methods 
public void initRun(){
    RNmedinh.set(  0);
    RNMEDinh_out.set(  0);
     RNmedinhtm=0.006;
     RNmedinhTONIC=10;
     RNmedinhK=0.16;
     RNmedinhsigma1=-10;
     RNmedinhsigma2=10;
     RNmedinhsigma3=0;
     RNmedinhsigma4=10;
}

public void simRun() {
	  /* <Q> SNRmedburst_in */
  // System.err.println("@@@@ RNMEDinh simRun entered @@@@");
    RNmedinh.set(system.nsldiff.eval(RNmedinh,RNmedinhtm,__tempRNMEDinh3.setReference(NslSub.eval(__tempRNMEDinh3.get(), __tempRNMEDinh2.setReference(NslAdd.eval(__tempRNMEDinh2.get(), __tempRNMEDinh0.setReference(NslSub.eval(__tempRNMEDinh0.get(), 0, RNmedinh)), RNmedinhTONIC)), (__tempRNMEDinh1.setReference(NslElemMult.eval(__tempRNMEDinh1.get(), RNmedinhK, SNRmedburst_in)))))));

    RNMEDinh_out.set(Nsl2Sigmoid.eval(RNmedinh,RNmedinhsigma1,
                            RNmedinhsigma2,
                            RNmedinhsigma3,
                            RNmedinhsigma4));
  }
public void makeConn(){
}

	/******************************************************/
	/*                                                    */
	/* Generated by nslc.src.NslCompiler. Do not edit these lines! */
	/*                                                    */
	/******************************************************/

	/* Constructor and related methods */
	/* makeinst() declared variables */

	/* Formal parameters */
	int array_size;

	/* Temporary variables */
		NslDouble2 __tempRNMEDinh0 = new NslDouble2(1, 1);
		NslDouble2 __tempRNMEDinh1 = new NslDouble2(1, 1);
		NslDouble2 __tempRNMEDinh2 = new NslDouble2(1, 1);
		NslDouble2 __tempRNMEDinh3 = new NslDouble2(1, 1);

	/* GENERIC CONSTRUCTOR: */
	public RNMEDinh(String nslName, NslModule nslParent, int array_size)
{
		super(nslName, nslParent);
		this.array_size=array_size;
		initSys();
		makeInstRNMEDinh(nslName, nslParent, array_size);
	}

	public void makeInstRNMEDinh(String nslName, NslModule nslParent, int array_size)
{ 
		Object[] nslArgs=new Object[]{array_size};
		callFromConstructorTop(nslArgs);
		SNRmedburst_in = new NslDinDouble2("SNRmedburst_in", this, array_size, array_size);
		RNMEDinh_out = new NslDoutDouble2("RNMEDinh_out", this, array_size, array_size);
		RNmedinh = new NslDouble2("RNmedinh", this, array_size, array_size);
		callFromConstructorBottom();
	}

	/******************************************************/
	/*                                                    */
	/* End of automatic declaration statements.           */
	/*                                                    */
	/******************************************************/


}//end RNMEDinh

