package MaxSelectorModel.Vlayer.v1_1_1.src;

/*********************************/
/*                               */
/*   Importing all Nsl classes   */
/*                               */
/*********************************/

import nslj.src.system.*;
import nslj.src.cmd.*;
import nslj.src.lang.*;
import nslj.src.math.*;
import nslj.src.display.*;
import nslj.src.display.j3d.*;

/*********************************/

public class Vlayer extends NslJavaModule{

//NSL Version: 3_0_n
//Sif Version: 9
//libNickName: MaxSelectorModel
//moduleName:  Vlayer
//versionName: 1_1_1
//floatSubModules: true


//variables 
public  NslDinDouble1 u_in; // 
public  NslDoutDouble0 vf; // 
private NslDouble0 vp; // 
private NslDouble0 hv; // 
private double tau; // 

//methods 
public void initModule() 
{
	hv.nslSetAccess('W');
	vf.set(0);
	vp.set(0);
	tau=1.0;
	hv.set(  0.5);
}

public void simRun() 
{
	vp.set(  system.nsldiff.eval(vp, tau, __tempMaxSelectorModel_Vlayer_v1_1_1_src_Vlayer2.setReference(__tempMaxSelectorModel_Vlayer_v1_1_1_src_Vlayer1.setReference(__tempMaxSelectorModel_Vlayer_v1_1_1_src_Vlayer0.setReference(-vp.get()).get()+NslSum.eval(u_in)).get()-hv.get())));
	vf.set(  NslRamp.eval(vp));
}
public void makeConn(){
}

	/******************************************************/
	/*                                                    */
	/* Generated by nslc.src.NslCompiler. Do not edit these lines! */
	/*                                                    */
	/******************************************************/

	/* Constructor and related methods */
	/* makeinst() declared variables */

	/* Formal parameters */
	int size;

	/* Temporary variables */
		NslDouble0 __tempMaxSelectorModel_Vlayer_v1_1_1_src_Vlayer0 = new NslDouble0();
		NslDouble0 __tempMaxSelectorModel_Vlayer_v1_1_1_src_Vlayer1 = new NslDouble0();
		NslDouble0 __tempMaxSelectorModel_Vlayer_v1_1_1_src_Vlayer2 = new NslDouble0();

	/* GENERIC CONSTRUCTOR: */
	public Vlayer(String nslName, NslModule nslParent, int size)
{
		super(nslName, nslParent);
		this.size=size;
		initSys();
		makeInstVlayer(nslName, nslParent, size);
	}

	public void makeInstVlayer(String nslName, NslModule nslParent, int size)
{ 
		Object[] nslArgs=new Object[]{size};
		callFromConstructorTop(nslArgs);
		u_in = new NslDinDouble1("u_in", this, size);
		vf = new NslDoutDouble0("vf", this);
		vp = new NslDouble0("vp", this);
		hv = new NslDouble0("hv", this);
		callFromConstructorBottom();
	}

	/******************************************************/
	/*                                                    */
	/* End of automatic declaration statements.           */
	/*                                                    */
	/******************************************************/


}//end Vlayer

