package DartModel.CEREB_module.v1_1_1.src;
import DartModel.GC_layer.v1_1_1.src.*;
import DartModel.IO_layer.v1_1_1.src.*;
import DartModel.PC_layer.v1_1_1.src.*;
import DartModel.NUC_layer.v1_1_1.src.*;

/*********************************/
/*                               */
/*   Importing all Nsl classes   */
/*                               */
/*********************************/

import nslj.src.system.*;
import nslj.src.cmd.*;
import nslj.src.lang.*;
import nslj.src.math.*;
import nslj.src.display.*;
import nslj.src.display.j3d.*;

/*********************************/

public class CEREB_module extends NslJavaModule{

//NSL Version: 3_0_n
//Sif Version: 9
//libNickName: DartModel
//moduleName:  CEREB_module
//versionName: 1_1_1
//floatSubModules: true


//variables 
public  GC_layer gc_l; // 
public  IO_layer io_l; // 
public  PC_layer pc_l; // 
public  NUC_layer nuc_l; // 
public  NslDinDouble1 sens_in; // SENS input (2x1)
public  NslDinDouble2 pp_in; // Parietal input (10x10)
public  NslDinDouble2 fcx_in; // Frontal cortex input (10x4)
public  NslDoutDouble1 cereb_out; // 
public  NslDoutDouble2 pc_out; // 
public  NslDoutDouble1 io_out; // 

//methods 
public void initModule()
{
	nslAddAreaCanvas("output", "cereb_out", cereb_out, 0, 50);
	nslAddAreaCanvas("output", "pc_out", pc_out, 0, 100);
	nslAddAreaCanvas("output", "io_out", io_out, 0, 10);
}
public void makeConn(){
    nslConnect(sens_in,io_l.sens_in);
    nslConnect(pp_in,gc_l.pp_in);
    nslConnect(pp_in,nuc_l.pp_in);
    nslConnect(fcx_in,gc_l.fcx_in);
    nslConnect(io_l.io_out,io_out);
    nslConnect(io_l.io_out,pc_l.io_in);
    nslConnect(nuc_l.nuc_out,cereb_out);
    nslConnect(nuc_l.nuc_out,io_l.nuc_in);
    nslConnect(pc_l.pc_out,pc_out);
    nslConnect(pc_l.pc_out,nuc_l.pc_in);
    nslConnect(gc_l.gc_out,pc_l.gc_in);
}

	/******************************************************/
	/*                                                    */
	/* Generated by nslc.src.NslCompiler. Do not edit these lines! */
	/*                                                    */
	/******************************************************/

	/* Constructor and related methods */
	/* makeinst() declared variables */

	/* Formal parameters */

	/* Temporary variables */

	/* GENERIC CONSTRUCTOR: */
	public CEREB_module(String nslName, NslModule nslParent)
{
		super(nslName, nslParent);
		initSys();
		makeInstCEREB_module(nslName, nslParent);
	}

	public void makeInstCEREB_module(String nslName, NslModule nslParent)
{ 
		Object[] nslArgs=new Object[]{};
		callFromConstructorTop(nslArgs);
		gc_l = new GC_layer("gc_l", this);
		io_l = new IO_layer("io_l", this);
		pc_l = new PC_layer("pc_l", this);
		nuc_l = new NUC_layer("nuc_l", this);
		sens_in = new NslDinDouble1("sens_in", this, 2);
		pp_in = new NslDinDouble2("pp_in", this, 10, 10);
		fcx_in = new NslDinDouble2("fcx_in", this, 10, 4);
		cereb_out = new NslDoutDouble1("cereb_out", this, 2);
		pc_out = new NslDoutDouble2("pc_out", this, 2, 5);
		io_out = new NslDoutDouble1("io_out", this, 2);
		callFromConstructorBottom();
	}

	/******************************************************/
	/*                                                    */
	/* End of automatic declaration statements.           */
	/*                                                    */
	/******************************************************/


}//end CEREB_module

