/** 
Dopamine is modelled as an inhibitory effect on the indirect
pathway projecting through GPe and STN and as an excitatory
effect on the direct pathway projecting to GPi/SNr.

Assume that the effect of dopamine on the projection neurons 
in the caudate is to manipulate the time constant of the neurons.  
More dopamine shortens the time constant of the neurons and 
less dopamine increases the time constant.
*/
package CrowleyModel.CDlatburst.v1_1_1.src;

/*********************************/
/*                               */
/*   Importing all Nsl classes   */
/*                               */
/*********************************/

import nslj.src.system.*;
import nslj.src.cmd.*;
import nslj.src.lang.*;
import nslj.src.math.*;
import nslj.src.display.*;
import nslj.src.display.j3d.*;

/*********************************/

public class CDlatburst extends NslModule{

//NSL Version: 3_0_n
//Sif Version: 9
//libNickName: CrowleyModel
//moduleName:  CDlatburst
//versionName: 1_1_1
//floatSubModules: true


//variables 
public  NslDinDouble2 FEFsac_in; // 
public  NslDinDouble2 SNCdop_in; // 
public  NslDinDouble2 PFCgo_in; // 
public  NslDinDouble2 PFCfovea_in; // 
public  NslDinDouble2 CDlattan_in; // 
public  NslDoutDouble2 CDindlatburst_out; // 
public  NslDoutDouble2 CDdirlatburst_out; // 
private  NslDouble2 cdindlatburst; // 
private  NslDouble2 cddirlatburst; // 
private double CorticalSlowDown; // 
private double basecdlatbursttm; // 
private double cdlatbursttm; // 
private double CDlatfefsacK; // 
private double CDlattanK; // 
private double CDlatsncK; // 
private double CDlatpfcK; // 
private double CDlatpfcgoK; // 
private double CDlbsigma1; // 
private double CDlbsigma2; // 
private double CDlbsigma3; // 
private double CDlbsigma4; // 

//methods 
public void initRun () 
{
	CDindlatburst_out.set(0);
	CDdirlatburst_out.set(0);

	CorticalSlowDown = 1.;
	basecdlatbursttm = 0.01;
	cdlatbursttm = basecdlatbursttm*CorticalSlowDown ;
	CDlatfefsacK = 0.85;
	CDlattanK = 2;
	CDlatsncK = 1;
	CDlatpfcK = 0.25;
	CDlatpfcgoK = 0.25;
	CDlbsigma1 = 0;
	CDlbsigma2 = 60; // 90; //99/8/2 aa ???
	CDlbsigma3 = 0;
	CDlbsigma4 = 60;
}

public void simRun () 
{
	cdindlatburst.set(  system.nsldiff.eval (cdindlatburst,cdlatbursttm, 
		__tempCDlatburst8.setReference(NslAdd.eval(__tempCDlatburst8.get(), __tempCDlatburst7.setReference(NslSub.eval(__tempCDlatburst7.get(), __tempCDlatburst6.setReference(NslSub.eval(__tempCDlatburst6.get(), __tempCDlatburst5.setReference(NslAdd.eval(__tempCDlatburst5.get(), __tempCDlatburst0.setReference(NslSub.eval(__tempCDlatburst0.get(), 0, cdindlatburst)), (__tempCDlatburst1.setReference(NslElemMult.eval(__tempCDlatburst1.get(), CDlatfefsacK, FEFsac_in))))), (__tempCDlatburst2.setReference(NslElemMult.eval(__tempCDlatburst2.get(), CDlattanK, CDlattan_in))))), (__tempCDlatburst3.setReference(NslElemMult.eval(__tempCDlatburst3.get(), CDlatsncK, SNCdop_in))))), (__tempCDlatburst4.setReference(NslElemMult.eval(__tempCDlatburst4.get(), CDlatpfcK, PFCfovea_in)))))));
	CDindlatburst_out.set(  Nsl2Sigmoid.eval(cdindlatburst,CDlbsigma1, CDlbsigma2, CDlbsigma3, CDlbsigma4));

	cddirlatburst.set(  system.nsldiff.eval (cddirlatburst,cdlatbursttm, 
		__tempCDlatburst17.setReference(NslAdd.eval(__tempCDlatburst17.get(), __tempCDlatburst16.setReference(NslSub.eval(__tempCDlatburst16.get(), __tempCDlatburst15.setReference(NslAdd.eval(__tempCDlatburst15.get(), __tempCDlatburst14.setReference(NslAdd.eval(__tempCDlatburst14.get(), __tempCDlatburst9.setReference(NslSub.eval(__tempCDlatburst9.get(), 0, cddirlatburst)), (__tempCDlatburst10.setReference(NslElemMult.eval(__tempCDlatburst10.get(), CDlatfefsacK, FEFsac_in))))), (__tempCDlatburst11.setReference(NslElemMult.eval(__tempCDlatburst11.get(), CDlatpfcgoK, PFCgo_in))))), (__tempCDlatburst12.setReference(NslElemMult.eval(__tempCDlatburst12.get(), CDlattanK, CDlattan_in))))), (__tempCDlatburst13.setReference(NslElemMult.eval(__tempCDlatburst13.get(), CDlatsncK, SNCdop_in)))))));

	CDdirlatburst_out.set(  Nsl2Sigmoid.eval(cddirlatburst, CDlbsigma1, CDlbsigma2, CDlbsigma3, CDlbsigma4));
}
public void makeConn(){
}

	/******************************************************/
	/*                                                    */
	/* Generated by nslc.src.NslCompiler. Do not edit these lines! */
	/*                                                    */
	/******************************************************/

	/* Constructor and related methods */
	/* makeinst() declared variables */

	/* Formal parameters */
	int CorticalArraySize;

	/* Temporary variables */
		NslDouble2 __tempCDlatburst0 = new NslDouble2(1, 1);
		NslDouble2 __tempCDlatburst1 = new NslDouble2(1, 1);
		NslDouble2 __tempCDlatburst2 = new NslDouble2(1, 1);
		NslDouble2 __tempCDlatburst3 = new NslDouble2(1, 1);
		NslDouble2 __tempCDlatburst4 = new NslDouble2(1, 1);
		NslDouble2 __tempCDlatburst5 = new NslDouble2(1, 1);
		NslDouble2 __tempCDlatburst6 = new NslDouble2(1, 1);
		NslDouble2 __tempCDlatburst7 = new NslDouble2(1, 1);
		NslDouble2 __tempCDlatburst8 = new NslDouble2(1, 1);
		NslDouble2 __tempCDlatburst9 = new NslDouble2(1, 1);
		NslDouble2 __tempCDlatburst10 = new NslDouble2(1, 1);
		NslDouble2 __tempCDlatburst11 = new NslDouble2(1, 1);
		NslDouble2 __tempCDlatburst12 = new NslDouble2(1, 1);
		NslDouble2 __tempCDlatburst13 = new NslDouble2(1, 1);
		NslDouble2 __tempCDlatburst14 = new NslDouble2(1, 1);
		NslDouble2 __tempCDlatburst15 = new NslDouble2(1, 1);
		NslDouble2 __tempCDlatburst16 = new NslDouble2(1, 1);
		NslDouble2 __tempCDlatburst17 = new NslDouble2(1, 1);

	/* GENERIC CONSTRUCTOR: */
	public CDlatburst(String nslName, NslModule nslParent, int CorticalArraySize)
{
		super(nslName, nslParent);
		this.CorticalArraySize=CorticalArraySize;
		initSys();
		makeInstCDlatburst(nslName, nslParent, CorticalArraySize);
	}

	public void makeInstCDlatburst(String nslName, NslModule nslParent, int CorticalArraySize)
{ 
		Object[] nslArgs=new Object[]{CorticalArraySize};
		callFromConstructorTop(nslArgs);
		FEFsac_in = new NslDinDouble2("FEFsac_in", this, CorticalArraySize, CorticalArraySize);
		SNCdop_in = new NslDinDouble2("SNCdop_in", this, CorticalArraySize, CorticalArraySize);
		PFCgo_in = new NslDinDouble2("PFCgo_in", this, CorticalArraySize, CorticalArraySize);
		PFCfovea_in = new NslDinDouble2("PFCfovea_in", this, CorticalArraySize, CorticalArraySize);
		CDlattan_in = new NslDinDouble2("CDlattan_in", this, CorticalArraySize, CorticalArraySize);
		CDindlatburst_out = new NslDoutDouble2("CDindlatburst_out", this, CorticalArraySize, CorticalArraySize);
		CDdirlatburst_out = new NslDoutDouble2("CDdirlatburst_out", this, CorticalArraySize, CorticalArraySize);
		cdindlatburst = new NslDouble2("cdindlatburst", this, CorticalArraySize, CorticalArraySize);
		cddirlatburst = new NslDouble2("cddirlatburst", this, CorticalArraySize, CorticalArraySize);
		callFromConstructorBottom();
	}

	/******************************************************/
	/*                                                    */
	/* End of automatic declaration statements.           */
	/*                                                    */
	/******************************************************/


}//end CDlatburst

