/** 
 Here is the class representing the LimbicCortex (LC) input module.
 In old NSL it is an input array, but since NSLJ does not have
 input arrays yet we make them static arrays.
*/
package CrowleyModel.LC.v1_1_1.src;

/*********************************/
/*                               */
/*   Importing all Nsl classes   */
/*                               */
/*********************************/

import nslj.src.system.*;
import nslj.src.cmd.*;
import nslj.src.lang.*;
import nslj.src.math.*;
import nslj.src.display.*;
import nslj.src.display.j3d.*;

/*********************************/

public class LC extends NslModule{

//NSL Version: 3_0_n
//Sif Version: 9
//libNickName: CrowleyModel
//moduleName:  LC
//versionName: 1_1_1
//floatSubModules: true


//variables 
public  NslDoutDouble2 LimbicCortex_out; // 

//methods 
public void initRun(){
    LimbicCortex_out.set(30);
  }
public void makeConn(){
}

	/******************************************************/
	/*                                                    */
	/* Generated by nslc.src.NslCompiler. Do not edit these lines! */
	/*                                                    */
	/******************************************************/

	/* Constructor and related methods */
	/* makeinst() declared variables */

	/* Formal parameters */
	int array_size;

	/* Temporary variables */

	/* GENERIC CONSTRUCTOR: */
	public LC(String nslName, NslModule nslParent, int array_size)
{
		super(nslName, nslParent);
		this.array_size=array_size;
		initSys();
		makeInstLC(nslName, nslParent, array_size);
	}

	public void makeInstLC(String nslName, NslModule nslParent, int array_size)
{ 
		Object[] nslArgs=new Object[]{array_size};
		callFromConstructorTop(nslArgs);
		LimbicCortex_out = new NslDoutDouble2("LimbicCortex_out", this, array_size, array_size);
		callFromConstructorBottom();
	}

	/******************************************************/
	/*                                                    */
	/* End of automatic declaration statements.           */
	/*                                                    */
	/******************************************************/


}//end LC

