/** 
 CDmedinh class
 Represents the Caudate Non-dopaminergic Interneuron Cells Layer
 see     CDmedinh
 version 0.1 96-11-19
 author  Michael Crowley
 -var public FEFsac_in - input coming from FEF module (of type NslDouble2)
 -var public LIPmem_in - input coming from LIP module (of type NslDouble2)
 -var public CDmedinh_out - output going to CDmedtan module (of type NslDouble2)
*/
package CrowleyModel.CDmedinh.v1_1_1.src;
import CrowleyModel.Func.v1_1_1.src.*;

/*********************************/
/*                               */
/*   Importing all Nsl classes   */
/*                               */
/*********************************/

import nslj.src.system.*;
import nslj.src.cmd.*;
import nslj.src.lang.*;
import nslj.src.math.*;
import nslj.src.display.*;
import nslj.src.display.j3d.*;

/*********************************/

public class CDmedinh extends NslModule{

//NSL Version: 3_0_n
//Sif Version: 9
//libNickName: CrowleyModel
//moduleName:  CDmedinh
//versionName: 1_1_1
//floatSubModules: true


//variables 
public  NslDinInt3 FEFxmap_bulk; // 
public  NslDinInt3 FEFymap_bulk; // 
public  NslDinInt3 LIPxmap_bulk; // 
public  NslDinInt3 LIPymap_bulk; // 
public  NslDinDouble2 FEFsac_in; // 
public  NslDinDouble2 LIPmem_in; // 
public  NslDoutDouble2 CDmedinh_out; // 
private double cdmedinhtm; // 
private double CDlisigma1; // 
private double CDlisigma2; // 
private double CDlisigma3; // 
private double CDlisigma4; // 
private  NslDouble2 CDfefinput; // 
private  NslDouble2 CDlipinput; // 
private  NslDouble2 cdmedinh; // 
public  Func func; // 

//methods 
public void initRun () 
{
	CDmedinh_out.set( 0);
	cdmedinhtm = 0.01;
	CDlisigma1 = 45;
	CDlisigma2 = 90;
	CDlisigma3 = 0;
	CDlisigma4 = 60;
}

public void simRun () 
{
	int tempint;

	// System.err.println("@@@@ CDmedinh simRun entered @@@@");

	tempint = func.SetCD (CDfefinput, FEFxmap_bulk , FEFymap_bulk , FEFsac_in);
	tempint = func.SetCD (CDlipinput, LIPxmap_bulk , LIPymap_bulk , LIPmem_in);

	cdmedinh.set(  system.nsldiff.eval (cdmedinh,cdmedinhtm, __tempCDmedinh2.setReference(NslAdd.eval(__tempCDmedinh2.get(), __tempCDmedinh1.setReference(NslAdd.eval(__tempCDmedinh1.get(), __tempCDmedinh0.setReference(NslSub.eval(__tempCDmedinh0.get(), 0, cdmedinh)), CDfefinput)), CDlipinput)) ));

	CDmedinh_out.set(  Nsl2Sigmoid.eval(cdmedinh,CDlisigma1, CDlisigma2,
                                     CDlisigma3, CDlisigma4));
}
public void makeConn(){
}

	/******************************************************/
	/*                                                    */
	/* Generated by nslc.src.NslCompiler. Do not edit these lines! */
	/*                                                    */
	/******************************************************/

	/* Constructor and related methods */
	/* makeinst() declared variables */

	/* Formal parameters */
	int CorticalArraySize;
	int StriatalArraySize;

	/* Temporary variables */
		NslDouble2 __tempCDmedinh0 = new NslDouble2(1, 1);
		NslDouble2 __tempCDmedinh1 = new NslDouble2(1, 1);
		NslDouble2 __tempCDmedinh2 = new NslDouble2(1, 1);

	/* GENERIC CONSTRUCTOR: */
	public CDmedinh(String nslName, NslModule nslParent, int CorticalArraySize, int StriatalArraySize)
{
		super(nslName, nslParent);
		this.CorticalArraySize=CorticalArraySize;
		this.StriatalArraySize=StriatalArraySize;
		initSys();
		makeInstCDmedinh(nslName, nslParent, CorticalArraySize, StriatalArraySize);
	}

	public void makeInstCDmedinh(String nslName, NslModule nslParent, int CorticalArraySize, int StriatalArraySize)
{ 
		Object[] nslArgs=new Object[]{CorticalArraySize, StriatalArraySize};
		callFromConstructorTop(nslArgs);
		FEFxmap_bulk = new NslDinInt3("FEFxmap_bulk", this, CorticalArraySize, CorticalArraySize, CorticalArraySize);
		FEFymap_bulk = new NslDinInt3("FEFymap_bulk", this, CorticalArraySize, CorticalArraySize, CorticalArraySize);
		LIPxmap_bulk = new NslDinInt3("LIPxmap_bulk", this, CorticalArraySize, CorticalArraySize, CorticalArraySize);
		LIPymap_bulk = new NslDinInt3("LIPymap_bulk", this, CorticalArraySize, CorticalArraySize, CorticalArraySize);
		FEFsac_in = new NslDinDouble2("FEFsac_in", this, CorticalArraySize, CorticalArraySize);
		LIPmem_in = new NslDinDouble2("LIPmem_in", this, CorticalArraySize, CorticalArraySize);
		CDmedinh_out = new NslDoutDouble2("CDmedinh_out", this, StriatalArraySize, StriatalArraySize);
		CDfefinput = new NslDouble2("CDfefinput", this, StriatalArraySize, StriatalArraySize);
		CDlipinput = new NslDouble2("CDlipinput", this, StriatalArraySize, StriatalArraySize);
		cdmedinh = new NslDouble2("cdmedinh", this, StriatalArraySize, StriatalArraySize);
		func = new Func("func", this, CorticalArraySize);
		callFromConstructorBottom();
	}

	/******************************************************/
	/*                                                    */
	/* End of automatic declaration statements.           */
	/*                                                    */
	/******************************************************/


}//end CDmedinh

