package DomineyModel.VisCortex.v1_1_1.src;

/*********************************/
/*                               */
/*   Importing all Nsl classes   */
/*                               */
/*********************************/

import nslj.src.system.*;
import nslj.src.cmd.*;
import nslj.src.lang.*;
import nslj.src.math.*;
import nslj.src.display.*;
import nslj.src.display.j3d.*;

/*********************************/

public class VisCortex extends NslModule{

//NSL Version: 3_0_n
//Sif Version: 9
//libNickName: DomineyModel
//moduleName:  VisCortex
//versionName: 1_1_1
//floatSubModules: true


//variables 
public  NslDinFloat2 retina; // 
public  NslDoutFloat2 posteriorParietal; // 
private NslFloat0 posteriorParietal_tm; // 
private NslFloat0 arrMT_tm; // 
private NslFloat0 arrV4_tm; // 
private NslFloat0 arrV2_tm; // 
private NslFloat0 arrV1_tm; // 
private NslFloat0 arrLGN_tm; // 
private  NslFloat2 arrMT; // 
private  NslFloat2 arrV4; // 
private  NslFloat2 arrV2; // 
private  NslFloat2 arrV1; // 
private  NslFloat2 arrLGN; // 

//methods 
public void initRun() 
{
	posteriorParietal.set(0);
	arrMT.set(0);
	arrV4.set(0);
	arrV2.set(0);
	arrV1.set(0);
	arrLGN.set(0);

	posteriorParietal_tm.set( 0.006);  
	arrMT_tm.set( 0.006);  
	arrV4_tm.set( 0.006);
	arrV2_tm.set( 0.006);  
	arrV1_tm.set( 0.006);  
	arrLGN_tm.set( 0.006);  
}

public void simRun() 
{
	if (system.debug>=16) 
	{
		system.nslPrintln("debug: VisCortex: retina "+retina.toString());
	}

	posteriorParietal.set(system.nsldiff.eval(posteriorParietal,posteriorParietal_tm,__tempVisCortex1.setReference(NslAdd.eval(__tempVisCortex1.get(), __tempVisCortex0.setReference(NslSub.eval(__tempVisCortex0.get(), 0, posteriorParietal)), arrMT)) ));
	arrMT.set(system.nsldiff.eval(arrMT,arrMT_tm, __tempVisCortex3.setReference(NslAdd.eval(__tempVisCortex3.get(), __tempVisCortex2.setReference(NslSub.eval(__tempVisCortex2.get(), 0, arrMT)), arrV4)) ));
	arrV4.set(system.nsldiff.eval(arrV4,arrV4_tm, __tempVisCortex5.setReference(NslAdd.eval(__tempVisCortex5.get(), __tempVisCortex4.setReference(NslSub.eval(__tempVisCortex4.get(), 0, arrV4)), arrV2)) ));
	arrV2.set(system.nsldiff.eval(arrV2,arrV2_tm, __tempVisCortex7.setReference(NslAdd.eval(__tempVisCortex7.get(), __tempVisCortex6.setReference(NslSub.eval(__tempVisCortex6.get(), 0, arrV2)), arrV1)) ));
	arrV1.set(system.nsldiff.eval(arrV1,arrV1_tm, __tempVisCortex9.setReference(NslAdd.eval(__tempVisCortex9.get(), __tempVisCortex8.setReference(NslSub.eval(__tempVisCortex8.get(), 0, arrV1)), arrLGN)) ));
	arrLGN.set(system.nsldiff.eval(arrLGN,arrLGN_tm, __tempVisCortex11.setReference(NslAdd.eval(__tempVisCortex11.get(), __tempVisCortex10.setReference(NslSub.eval(__tempVisCortex10.get(), 0, arrLGN)), retina)) ));

	if (system.debug>=16) 
	{
		system.nslPrintln("VisCortex: simRun: posteriorParietal ");
		system.nslPrintln(posteriorParietal);
	}
}
public void makeConn(){
}

	/******************************************************/
	/*                                                    */
	/* Generated by nslc.src.NslCompiler. Do not edit these lines! */
	/*                                                    */
	/******************************************************/

	/* Constructor and related methods */
	/* makeinst() declared variables */

	/* Formal parameters */
	int stdsz;

	/* Temporary variables */
		NslFloat2 __tempVisCortex0 = new NslFloat2(1, 1);
		NslFloat2 __tempVisCortex1 = new NslFloat2(1, 1);
		NslFloat2 __tempVisCortex2 = new NslFloat2(1, 1);
		NslFloat2 __tempVisCortex3 = new NslFloat2(1, 1);
		NslFloat2 __tempVisCortex4 = new NslFloat2(1, 1);
		NslFloat2 __tempVisCortex5 = new NslFloat2(1, 1);
		NslFloat2 __tempVisCortex6 = new NslFloat2(1, 1);
		NslFloat2 __tempVisCortex7 = new NslFloat2(1, 1);
		NslFloat2 __tempVisCortex8 = new NslFloat2(1, 1);
		NslFloat2 __tempVisCortex9 = new NslFloat2(1, 1);
		NslFloat2 __tempVisCortex10 = new NslFloat2(1, 1);
		NslFloat2 __tempVisCortex11 = new NslFloat2(1, 1);

	/* GENERIC CONSTRUCTOR: */
	public VisCortex(String nslName, NslModule nslParent, int stdsz)
{
		super(nslName, nslParent);
		this.stdsz=stdsz;
		initSys();
		makeInstVisCortex(nslName, nslParent, stdsz);
	}

	public void makeInstVisCortex(String nslName, NslModule nslParent, int stdsz)
{ 
		Object[] nslArgs=new Object[]{stdsz};
		callFromConstructorTop(nslArgs);
		retina = new NslDinFloat2("retina", this, stdsz, stdsz);
		posteriorParietal = new NslDoutFloat2("posteriorParietal", this, stdsz, stdsz);
		posteriorParietal_tm = new NslFloat0("posteriorParietal_tm", this);
		arrMT_tm = new NslFloat0("arrMT_tm", this);
		arrV4_tm = new NslFloat0("arrV4_tm", this);
		arrV2_tm = new NslFloat0("arrV2_tm", this);
		arrV1_tm = new NslFloat0("arrV1_tm", this);
		arrLGN_tm = new NslFloat0("arrLGN_tm", this);
		arrMT = new NslFloat2("arrMT", this, stdsz, stdsz);
		arrV4 = new NslFloat2("arrV4", this, stdsz, stdsz);
		arrV2 = new NslFloat2("arrV2", this, stdsz, stdsz);
		arrV1 = new NslFloat2("arrV1", this, stdsz, stdsz);
		arrLGN = new NslFloat2("arrLGN", this, stdsz, stdsz);
		callFromConstructorBottom();
	}

	/******************************************************/
	/*                                                    */
	/* End of automatic declaration statements.           */
	/*                                                    */
	/******************************************************/


}//end VisCortex

