package MaxSelectorModelMatlab.MVlayer.v1_1_1.src;

/*********************************/
/*                               */
/*   Importing all Nsl classes   */
/*                               */
/*********************************/

import nslj.src.system.*;
import nslj.src.cmd.*;
import nslj.src.lang.*;
import nslj.src.math.*;
import nslj.src.display.*;
import nslj.src.display.j3d.*;

/*********************************/

public class MVlayer extends NslMatlabModule{

//NSL Version: 3_0_n
//Sif Version: 9
//libNickName: MaxSelectorModelMatlab
//moduleName:  MVlayer
//versionName: 1_1_1
//floatSubModules: true


//variables 
public  NslDinDouble1 u_in; // 
public  NslDoutDouble0 vf; // 
private NslDouble0 vp; // 
private NslDouble0 h2; // 
private NslDouble0 tau; // 

//methods 

public void makeConn(){
}

	/******************************************************/
	/*                                                    */
	/* Generated by nslc.src.NslCompiler. Do not edit these lines! */
	/*                                                    */
	/******************************************************/

	/* Constructor and related methods */
	/* makeinst() declared variables */

	/* Formal parameters */
	int size;

	/* Temporary variables */

	/* GENERIC CONSTRUCTOR: */
	public MVlayer(String nslName, NslModule nslParent, int size)
{
		super(nslName, nslParent);
		this.size=size;
		initSys();
		makeInstMVlayer(nslName, nslParent, size);
	}

	public void makeInstMVlayer(String nslName, NslModule nslParent, int size)
{ 
		Object[] nslArgs=new Object[]{size};
		callFromConstructorTop(nslArgs);
		u_in = new NslDinDouble1("u_in", this, size);
		vf = new NslDoutDouble0("vf", this);
		vp = new NslDouble0("vp", this);
		h2 = new NslDouble0("h2", this);
		tau = new NslDouble0("tau", this);
		callFromConstructorBottom();
	}

	/******************************************************/
	/*                                                    */
	/* End of automatic declaration statements.           */
	/*                                                    */
	/******************************************************/


}//end MVlayer

