package scs.ui;

import scs.util.UserPref;

import javax.swing.*;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.*;

public class PortOptionsDialog extends JDialog implements ActionListener
{
    protected SchEditorFrame parent;

    private JPanel contentPane;
    private JButton buttonOK;
    private JButton buttonCancel;
    private JLabel inputPortShapeLabel;
    private JComboBox inputPortShapeComboBox;
    private JLabel outputPortShapeLabel;
    private JComboBox outputPortShapeComboBox;

    public PortOptionsDialog(SchEditorFrame fm)
    {
        super(fm, "Port Shape Options", true);

        parent = fm;

        inputPortShapeComboBox.addItem("DEFAULT");
        inputPortShapeComboBox.setSelectedItem(UserPref.input_port_shape);

        outputPortShapeComboBox.addItem("DEFAULT");
        outputPortShapeComboBox.addItem("CROSS");
        outputPortShapeComboBox.addItem("ARROW");
        outputPortShapeComboBox.setSelectedItem(UserPref.output_port_shape);

        buttonOK.addActionListener(this);
        buttonCancel.addActionListener(this);

        setContentPane(contentPane);
        getRootPane().setDefaultButton(buttonOK);
    }

    public void actionPerformed(ActionEvent event)
    {
        if (event.getSource() instanceof JButton)
        {
            String cmdName = ((JButton) event.getSource()).getText();
            if (cmdName.equals("OK"))
            {
                UserPref.input_port_shape = inputPortShapeComboBox.getSelectedItem().toString();
                UserPref.output_port_shape = outputPortShapeComboBox.getSelectedItem().toString();
                UserPref.save();

                if (parent.currModule != null && parent.currModule.mySchematic != null)
                    parent.currModule.mySchematic.refresh();

                dispose();
            }
            if (cmdName.equals("Cancel"))
            {
                dispose();
            }
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$()
    {
        contentPane = new JPanel();
        contentPane.setLayout(new GridBagLayout());
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        contentPane.add(panel1, gbc);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel1.add(panel2, gbc);
        buttonOK = new JButton();
        buttonOK.setText("OK");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(buttonOK, gbc);
        buttonCancel = new JButton();
        buttonCancel.setText("Cancel");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(buttonCancel, gbc);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        contentPane.add(panel3, gbc);
        inputPortShapeLabel = new JLabel();
        inputPortShapeLabel.setText("Input Port Shape");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel3.add(inputPortShapeLabel, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel3.add(spacer1, gbc);
        inputPortShapeComboBox = new JComboBox();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel3.add(inputPortShapeComboBox, gbc);
        outputPortShapeLabel = new JLabel();
        outputPortShapeLabel.setText("Output Port Shape");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        panel3.add(outputPortShapeLabel, gbc);
        outputPortShapeComboBox = new JComboBox();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel3.add(outputPortShapeComboBox, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$()
    {
        return contentPane;
    }
}
