package scs.ui;

import scs.util.SCSUtility;

import javax.swing.*;
import java.awt.event.*;
import java.awt.*;

public class ReplaceDialog extends JDialog implements ActionListener
{
    boolean okPressed = false;

    private JPanel contentPane;
    private JButton buttonOK;
    private JButton buttonCancel;
    private JLabel findLabel;
    private JTextField findTextField;
    private JLabel replaceLabel;
    private JTextField replaceTextField;
    private JLabel directionLabel;
    private JRadioButton forwardRadioButton;
    private JRadioButton backwardRadioButton;
    private JCheckBox globalCheckBox;

    public ReplaceDialog(Frame fm)
    {
        super(fm, "Replace Dialog ", true); //blocking true

        setContentPane(contentPane);
        getRootPane().setDefaultButton(buttonOK);

        initReplaceDialog("", "", false);
    }

    public ReplaceDialog(Frame fm, String lastFind, String lastReplace)
    {
        super(fm, "Replace Again Dialog ", true); //blocking true

        setContentPane(contentPane);
        getRootPane().setDefaultButton(buttonOK);

        initReplaceDialog(lastFind, lastReplace, false);
    }

    public ReplaceDialog(Frame fm, String lastFind, String lastReplace, boolean global)
    {
        super(fm, "Replace Again Dialog ", true); //blocking true

        setContentPane(contentPane);
        getRootPane().setDefaultButton(buttonOK);

        initReplaceDialog(lastFind, lastReplace, global);
    }

    public void initReplaceDialog(String lastFind, String lastReplace, boolean global)
    {
        findTextField.setText(lastFind);
        replaceTextField.setText(lastReplace);
        forwardRadioButton.setSelected(true);
        globalCheckBox.setSelected(global);
        buttonOK.addActionListener(this);
        buttonCancel.addActionListener(this);

        addWindowListener(new DWAdapter(this));
    }

    /*
     * actionPerformed - Handle action events.
     */
    public void actionPerformed(ActionEvent event)
    {
        JButton bn;
        String bntext;

        if (event.getSource() instanceof JButton)
        {
            bn = (JButton) event.getSource();
            bntext = bn.getText();

            if (bntext.equals("OK"))
            {
                okPressed = true;
                dispose();
            }
            if (bntext.equals("Cancel"))
            {
                okPressed = false;
                dispose();
            }
        }
    }

    public String getFindString()
    {
        return findTextField.getText();
    }

    public String getReplaceString()
    {
        return replaceTextField.getText();
    }

    public boolean isForward()
    {
        return forwardRadioButton.isSelected();
    }

    public boolean isGlobal()
    {
        return globalCheckBox.isSelected();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$()
    {
        contentPane = new JPanel();
        contentPane.setLayout(new GridBagLayout());
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        contentPane.add(panel1, gbc);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel1.add(panel2, gbc);
        buttonOK = new JButton();
        buttonOK.setText("OK");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(buttonOK, gbc);
        buttonCancel = new JButton();
        buttonCancel.setText("Cancel");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(buttonCancel, gbc);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        contentPane.add(panel3, gbc);
        findLabel = new JLabel();
        findLabel.setText("Find:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel3.add(findLabel, gbc);
        findTextField = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        gbc.weightx = 0.1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel3.add(findTextField, gbc);
        replaceLabel = new JLabel();
        replaceLabel.setText("Replace With:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        panel3.add(replaceLabel, gbc);
        replaceTextField = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel3.add(replaceTextField, gbc);
        directionLabel = new JLabel();
        directionLabel.setText("Direction:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        panel3.add(directionLabel, gbc);
        forwardRadioButton = new JRadioButton();
        forwardRadioButton.setText("Forward");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        panel3.add(forwardRadioButton, gbc);
        backwardRadioButton = new JRadioButton();
        backwardRadioButton.setText("Backward");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        panel3.add(backwardRadioButton, gbc);
        globalCheckBox = new JCheckBox();
        globalCheckBox.setText("Global Replace");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        panel3.add(globalCheckBox, gbc);
        ButtonGroup buttonGroup;
        buttonGroup = new ButtonGroup();
        buttonGroup.add(forwardRadioButton);
        buttonGroup.add(backwardRadioButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$()
    {
        return contentPane;
    }

    class DWAdapter extends WindowAdapter
    {
        JDialog d;

        public DWAdapter(JDialog d)
        {
            this.d = d;
        }

        public void windowClosing(WindowEvent event)
        {
            d.dispose();
        }
    }
}
