/** 
 Lat class
 Represents the Lateral Circuit
 @see    Lat
 @version 0.1 96/11/19
 @author  Michael Crowley
 -var public PFCgo_in - input coming from PFC module (of type NslDouble2)<p>
 -var public SNCdop_in - input coming from SNC module (of type NslDouble2)<p>
 -var public PFCfovea_in - input coming from PFC module (of type NslDouble2)<p>
 -var public FEFsac_in - input coming from FEF module (of type NslDouble2)<p>
 -var public SNRlatburst_out - output going to SC module (of type NslDouble2)<p>
*/
package CrowleyModel.Lat.v1_1_1.src;
import CrowleyModel.CDlatinh.v1_1_1.src.*;
import CrowleyModel.CDlattan.v1_1_1.src.*;
import CrowleyModel.CDlatburst.v1_1_1.src.*;
import CrowleyModel.GPElatburst.v1_1_1.src.*;
import CrowleyModel.STNlatburst.v1_1_1.src.*;
import CrowleyModel.SNRlatburst.v1_1_1.src.*;

/*********************************/
/*                               */
/*   Importing all Nsl classes   */
/*                               */
/*********************************/

import nslj.src.system.*;
import nslj.src.cmd.*;
import nslj.src.lang.*;
import nslj.src.math.*;
import nslj.src.display.*;
import nslj.src.display.j3d.*;

/*********************************/

public class Lat extends NslModule{

//NSL Version: 3_0_n
//Sif Version: 9
//libNickName: CrowleyModel
//moduleName:  Lat
//versionName: 1_1_1
//floatSubModules: true


//variables 
public  NslDinDouble2 FEFsac_in; // 
public  NslDinDouble2 SNCdop_in; // 
public  NslDinDouble2 PFCgo_in; // 
public  NslDinDouble2 PFCfovea_in; // 
public  NslDoutDouble2 SNRlatburst_out; // 
public  CDlatinh cdlatinh; // 
public  CDlattan cdlattan; // 
public  CDlatburst cdlatburst; // 
public  GPElatburst gpelatburst; // 
public  STNlatburst stnlatburst; // 
public  SNRlatburst snrlatburst; // 

//methods 

public void makeConn(){
    nslConnect(FEFsac_in,cdlatinh.FEFsac_in);
    nslConnect(FEFsac_in,cdlatburst.FEFsac_in);
    nslConnect(PFCgo_in,cdlatinh.PFCgo_in);
    nslConnect(PFCgo_in,cdlatburst.PFCgo_in);
    nslConnect(SNCdop_in,cdlattan.SNCdop_in);
    nslConnect(SNCdop_in,cdlatburst.SNCdop_in);
    nslConnect(PFCfovea_in,cdlatburst.PFCfovea_in);
    nslConnect(cdlatinh.CDlatinh_out,cdlattan.CDlatinh_in);
    nslConnect(cdlattan.CDlattan_out,cdlatburst.CDlattan_in);
    nslConnect(cdlatburst.CDindlatburst_out,gpelatburst.CDindlatburst_in);
    nslConnect(cdlatburst.CDdirlatburst_out,snrlatburst.CDdirlatburst_in);
    nslConnect(gpelatburst.GPElatburst_out,stnlatburst.GPElatburst_in);
    nslConnect(stnlatburst.STNlatburst_out,snrlatburst.STNlatburst_in);
    nslConnect(snrlatburst.SNRlatburst_out,SNRlatburst_out);
}

	/******************************************************/
	/*                                                    */
	/* Generated by nslc.src.NslCompiler. Do not edit these lines! */
	/*                                                    */
	/******************************************************/

	/* Constructor and related methods */
	/* makeinst() declared variables */

	/* Formal parameters */
	int CorticalArraySize;

	/* Temporary variables */

	/* GENERIC CONSTRUCTOR: */
	public Lat(String nslName, NslModule nslParent, int CorticalArraySize)
{
		super(nslName, nslParent);
		this.CorticalArraySize=CorticalArraySize;
		initSys();
		makeInstLat(nslName, nslParent, CorticalArraySize);
	}

	public void makeInstLat(String nslName, NslModule nslParent, int CorticalArraySize)
{ 
		Object[] nslArgs=new Object[]{CorticalArraySize};
		callFromConstructorTop(nslArgs);
		FEFsac_in = new NslDinDouble2("FEFsac_in", this, CorticalArraySize, CorticalArraySize);
		SNCdop_in = new NslDinDouble2("SNCdop_in", this, CorticalArraySize, CorticalArraySize);
		PFCgo_in = new NslDinDouble2("PFCgo_in", this, CorticalArraySize, CorticalArraySize);
		PFCfovea_in = new NslDinDouble2("PFCfovea_in", this, CorticalArraySize, CorticalArraySize);
		SNRlatburst_out = new NslDoutDouble2("SNRlatburst_out", this, CorticalArraySize, CorticalArraySize);
		cdlatinh = new CDlatinh("cdlatinh", this, CorticalArraySize);
		cdlattan = new CDlattan("cdlattan", this, CorticalArraySize);
		cdlatburst = new CDlatburst("cdlatburst", this, CorticalArraySize);
		gpelatburst = new GPElatburst("gpelatburst", this, CorticalArraySize);
		stnlatburst = new STNlatburst("stnlatburst", this, CorticalArraySize);
		snrlatburst = new SNRlatburst("snrlatburst", this, CorticalArraySize);
		callFromConstructorBottom();
	}

	/******************************************************/
	/*                                                    */
	/* End of automatic declaration statements.           */
	/*                                                    */
	/******************************************************/


}//end Lat

